"""Serial synthesis with interruptible playback; cancellation keeps the model loaded."""
import contextlib
import json
import os
import re
import sys
import threading
import time
import uuid
import wave
import winsound
from concurrent.futures import ThreadPoolExecutor
from concurrent.futures import CancelledError


def check_cancelled(cancelled):
    if cancelled is not None and cancelled.is_set():
        raise CancelledError("Voice output cancelled")


@contextlib.contextmanager
def cancel_on_forward(module, cancelled):
    """Use PyTorch's native hook to stop between decoding steps, retaining weights."""
    if cancelled is None:
        yield
        return
    check_cancelled(cancelled)
    handle = module.register_forward_pre_hook(lambda *_: check_cancelled(cancelled))
    try:
        yield
    finally:
        handle.remove()


def prune_outputs(output_dir, keep=100, max_bytes=256 * 1024 * 1024, max_age=7 * 86400, protected=None):
    # Only UUID-named files generated by this worker are temporary audio.
    files = []
    for path in output_dir.glob("*.wav"):
        if path.is_file() and not path.is_symlink() and re.fullmatch(r"(?:piper|xtts|omnivoice|xvasynth)-[0-9a-f]{32}\.wav", path.name):
            with contextlib.suppress(OSError):
                files.append((path, path.stat()))
    total = 0
    for index, (path, stat) in enumerate(sorted(files, key=lambda item: item[1].st_mtime, reverse=True)):
        total += stat.st_size
        if path != protected and (index >= keep or total > max_bytes or time.time() - stat.st_mtime > max_age):
            with contextlib.suppress(OSError):
                path.unlink()


def serve(engine, engine_name, output_dir):
    output_dir.mkdir(parents=True, exist_ok=True)
    prune_outputs(output_dir)
    protocol = sys.stdout
    output_lock = threading.Lock()
    requests = {}

    def emit(payload):
        with output_lock:
            print(json.dumps({**payload, "workerPid": os.getpid()}, ensure_ascii=False), file=protocol, flush=True)

    def synthesize(request, cancelled):
        request_id = request["id"]
        output = output_dir / f"{engine_name}-{uuid.uuid4().hex}.wav"
        started = time.perf_counter()
        try:
            if cancelled.is_set():
                return
            text = str(request.get("text") or "").strip()
            if not text:
                raise ValueError("Voice output text is empty")
            with contextlib.redirect_stdout(sys.stderr):
                engine.synthesize(text, output, cancelled)
            check_cancelled(cancelled)
            synthesis_elapsed = time.perf_counter() - started
            with wave.open(str(output), "rb") as wav:
                duration = wav.getnframes() / wav.getframerate()
            if request.get("play", True) and not cancelled.is_set():
                try:
                    winsound.PlaySound(str(output), winsound.SND_FILENAME | winsound.SND_ASYNC)
                    cancelled.wait(duration)
                finally:
                    winsound.PlaySound(None, 0)
            if not cancelled.is_set():
                emit({"id": request_id, "success": True, "engine": engine_name, "wav": str(output),
                      "duration": round(duration, 3), "synthesisElapsed": round(synthesis_elapsed, 3),
                      "elapsed": round(time.perf_counter() - started, 3)})
        except Exception as error:
            if not cancelled.is_set():
                emit({"id": request_id, "success": False, "error": f"{type(error).__name__}: {error}"})
        finally:
            if cancelled.is_set():
                with contextlib.suppress(OSError):
                    output.unlink(missing_ok=True)
                emit({"id": request_id, "success": False, "error": "Voice output cancelled"})
            requests.pop(request_id, None)
            prune_outputs(output_dir, protected=output)

    emit({"type": "ready", "engine": engine_name})
    # One inference at a time, while stdin remains available to cancel playback.
    with ThreadPoolExecutor(max_workers=1) as executor:
        try:
            for line in sys.stdin:
                request = {}
                try:
                    request = json.loads(line)
                    request_id = request["id"]
                    if request.get("type") == "shutdown":
                        break
                    if request.get("type") == "cancel":
                        cancelled = requests.get(request_id)
                        if cancelled is not None:
                            cancelled.set()
                    elif request.get("type") == "speak":
                        cancelled = threading.Event()
                        requests[request_id] = cancelled
                        executor.submit(synthesize, request, cancelled)
                    else:
                        raise ValueError("Unsupported voice output request")
                except Exception as error:
                    emit({"id": request.get("id"), "success": False, "error": str(error)})
        finally:
            for cancelled in list(requests.values()):
                cancelled.set()
