const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), os = require('node:os');
const { app, BrowserWindow, ipcMain } = require('electron');
const installAssets = require('../electron/notes/assets.cjs');
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'localflow-editor-ui-')); app.setPath('userData', directory);
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
app.whenReady().then(async () => { let agent; try {
  const { TestClient } = await import('./agent-client-fixture.mjs'); require('../electron/codex-client.cjs').CodexClient = TestClient;
  const { createNiwaAgent } = await import('../electron/niwa-agent.mjs');
  const { storeUploads } = await import('../electron/notes/uploads.mjs');
  const window = new BrowserWindow({ width: 1440, height: 980, show: false, webPreferences: { sandbox: false, backgroundThrottling: false, additionalArguments: ['--workspace-check'], preload: path.join(__dirname, 'settings-ui-preload.cjs') } });
  agent = createNiwaAgent({ directory, appRoot: path.resolve('.'), binary: () => '', speak: async () => {}, notify: event => window.webContents.send('test-niwa-event', event) });
  await installAssets(path.join(directory, 'notes'));
  const errors = []; window.webContents.on('console-message', (_event, level, message) => { if (level >= 3) errors.push(message); });
  for (const method of ['list', 'read', 'importLegacy', 'create', 'save', 'remove', 'rename', 'move', 'duplicate', 'databaseRead', 'databaseSave', 'databaseAddRow']) ipcMain.handle(`workspace-notes-${method}`, (_event, value) => agent.notes[method](value));
  for (const method of ['snapshot', 'projects', 'configure']) ipcMain.handle(`workspace-${method}`, (_event, value) => agent[method](value));
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a+FkAAAAASUVORK5CYII=', 'base64');
  let uploads = 0, picks = 0;
  ipcMain.handle('workspace-notes-pick-assets', () => { picks++; return storeUploads(path.join(directory, 'notes'), [{ name: 'picked.png', data: png }]); });
  ipcMain.handle('workspace-notes-upload-assets', (_event, files) => { uploads++; return storeUploads(path.join(directory, 'notes'), files); });
  const page = agent.notes.create({ label: 'Editor proof', content: 'First block\n\nSecond block\n\n第三段落' });
  await window.loadFile(path.resolve('dist/index.html'));
  const run = script => window.webContents.executeJavaScript(script).catch(error => { throw new Error(error.message + '\n' + script); });
  const wait = async script => { for (let i = 0; i < 100; i++) { if (await run(`Boolean(${script})`)) return; await pause(80); } throw new Error('Timed out: ' + script); };
  const click = selector => run(`document.querySelector(${JSON.stringify(selector)}).click()`);
  const textClick = (selector, text) => run(`[...document.querySelectorAll(${JSON.stringify(selector)})].find(e=>e.textContent===${JSON.stringify(text)}).click()`);
  const fill = (selector, value) => run(`{const e=document.querySelector(${JSON.stringify(selector)});Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(e,${JSON.stringify(value)});e.dispatchEvent(new Event('input',{bubbles:true}));}`);
  const context = async selector => { await run(`{const e=document.querySelector(${JSON.stringify(selector)}),r=document.createRange();r.selectNodeContents(e);getSelection().removeAllRanges();getSelection().addRange(r);document.dispatchEvent(new Event('selectionchange'));}`); await pause(80); await run(`{const e=document.querySelector(${JSON.stringify(selector)}),r=e.getBoundingClientRect();e.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:r.left+8,clientY:r.top+8}));}`); await wait("document.querySelector('.noteContextMenu')"); };
  const menuAction = async label => { await fill('[aria-label="Search actions"]', label); await textClick('.noteContextMenu button span', label); await pause(60); };
  const insert = async label => { await click('[aria-label="Insert block"]'); await textClick('.noteInsertCatalog button', label); };
  await wait("document.querySelector('.navList [data-section=notes]')"); await click('.navList [data-section=notes]'); await wait("document.querySelector('.noteProse')");
  assert.equal(await run("document.querySelectorAll('.noteFormatting,.noteInsertRow,.noteTableControls').length"), 0, 'no persistent formatting bars');
  const beforeInsert=await run("document.querySelector('.noteProse').innerHTML");
  await click('[aria-label="Insert block"]');await run("document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");
  assert.equal(await run("document.querySelector('.noteProse').innerHTML"),beforeInsert,'opening and cancelling the insert menu does not add empty blocks');
  await context('.noteProse > p'); await menuAction('Align center'); await wait("document.querySelector('.noteProse > p').style.textAlign==='center'");
  await click('[aria-label="Undo edit"]');await wait("document.querySelector('.noteProse > p').style.textAlign!=='center'");
  await click('[aria-label="Redo edit"]');await wait("document.querySelector('.noteProse > p').style.textAlign==='center'");

  await context('.noteProse > p'); await menuAction('Move block down');
  assert.equal(await run("document.querySelector('.noteProse > p').textContent"), 'Second block');
  await context('.noteProse > p'); await menuAction('2 columns'); await wait("document.querySelectorAll('[data-type=column]').length===2");
  await run("{const e=document.querySelectorAll('[data-type=column] p')[1];e.focus();const r=document.createRange();r.selectNodeContents(e);getSelection().removeAllRanges();getSelection().addRange(r);document.execCommand('insertText',false,'Keep right column');}");
  await context('[data-type=column] p'); await menuAction('Stack into one column'); await wait("!document.querySelector('[data-type=columns]')");
  assert((await run("document.querySelector('.noteProse').textContent")).includes('Keep right column'));
  await insert('Table…'); await fill('[aria-label="Table rows"]', '3'); await fill('[aria-label="Table columns"]', '4'); await textClick('.noteTablePicker button', 'Insert table'); await wait("document.querySelectorAll('.noteProse tr').length===3");
  await context('.noteProse th p'); await menuAction('Row below'); await wait("document.querySelectorAll('.noteProse tr').length===4");
  await context('.noteProse th p'); await menuAction('Column after'); assert.equal(await run("document.querySelectorAll('.noteProse tr:first-child>*').length"), 5);
  // Return to a plain block before image insertion.
  await context('.noteProse > p:last-child'); await menuAction('Align left');
  await insert('Image or file…'); await wait("document.querySelectorAll('.noteProse img').length===1"); assert.equal(picks, 1);
  const fileEvent = async type => run(`{const data=new DataTransfer();data.items.add(new File([Uint8Array.from(atob(${JSON.stringify(png.toString('base64'))}),c=>c.charCodeAt(0))],${JSON.stringify(type+'.png')},{type:'image/png'}));const e=document.querySelector('.noteProse');e.dispatchEvent(new ${type === 'paste' ? 'ClipboardEvent' : 'DragEvent'}('${type}',{bubbles:true,cancelable:true,${type === 'paste' ? 'clipboardData' : 'dataTransfer'}:data,clientX:e.getBoundingClientRect().left+40,clientY:e.getBoundingClientRect().top+20}));}`);
  await fileEvent('paste'); await wait("document.querySelectorAll('.noteProse img').length===2"); await fileEvent('drop'); await wait("document.querySelectorAll('.noteProse img').length===3"); assert.equal(uploads, 2);
  await wait("[...document.querySelectorAll('.noteProse img')].every(i=>i.complete&&i.naturalWidth>0)");
  await insert('Database…'); await fill('[aria-label="Database name or search"]', 'New embedded database'); await textClick('.noteInsertDialog button', 'Create new database'); await wait("document.querySelector('.noteDatabaseEmbed')");
  await wait("document.querySelector('.noteDatabaseEmbed .databaseNewButton')");
  await click('.noteDatabaseEmbed .databaseNewButton');await wait("document.querySelector('.noteDatabaseEmbed .notesDatabaseTable tbody input')");
  await fill('.noteDatabaseEmbed .notesDatabaseTable tbody input','Inline database row');
  await run("{const e=document.querySelector('.noteDatabaseEmbed .notesDatabaseTable tbody input');e.focus();e.dispatchEvent(new FocusEvent('focusout',{bubbles:true}));e.blur();}");
  await pause(300);
  const embeddedNode=agent.notes.list().items.find(item=>item.id===page.id).children.find(item=>item.kind==='database');
  assert.equal(agent.notes.databaseRead(embeddedNode.id).rows[0].values.title,'Inline database row');
  const inlineDb=agent.notes.databaseRead(embeddedNode.id);for(let index=0;index<5;index++)inlineDb.properties.push({id:'inline'+index,name:'Field '+index,type:'text'});agent.notes.databaseSave(inlineDb);
  await wait("document.querySelectorAll('.noteDatabaseEmbed .notesDatabaseTable th').length===8");
  assert(await run("{const area=document.querySelector('.noteDatabaseEmbed .databaseContent');area.dispatchEvent(new WheelEvent('wheel',{bubbles:true,cancelable:true,shiftKey:true,deltaY:400}));area.scrollLeft>0&&area.scrollWidth>area.clientWidth}"),'inline database supports Shift+wheel');
  await run("document.querySelector('.noteDatabaseEmbed .databaseContent').scrollLeft=0");
  await click('.noteDatabaseEmbed [aria-label="Database actions"]');
  assert.equal(await run("document.querySelectorAll('.noteContextMenu').length"),0,'database commands do not open text commands');
  await run("document.querySelector('.databaseContextMenu').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");
  await insert('Page…'); await fill('[aria-label="Database name or search"]', 'Linked child page'); await textClick('.noteInsertDialog button', 'Create new page'); await wait("[...document.querySelectorAll('.noteProse a')].some(e=>e.textContent==='Linked child page')");
  await pause(1000); const saved = agent.notes.read(page.id); assert(saved.document); assert(saved.content.includes('localflow-asset:')); assert(saved.content.includes('Keep right column')); assert(saved.content.includes('New embedded database'));
  const databases = agent.notes.list().items.find(item => item.id === page.id)?.children || []; assert(databases.some(item => item.kind === 'database' && item.label === 'New embedded database'));
  assert(databases.some(item => item.kind === 'note' && item.label === 'Linked child page'));
  const encoded = JSON.stringify(saved.document); assert(encoded.includes('textAlign')); assert(encoded.includes('picked.png') && encoded.includes('paste.png') && encoded.includes('drop.png'));
  await click('[aria-label="Insert block"]');
  window.showInactive();await pause(150);fs.mkdirSync(path.resolve('output/notes-editing'),{recursive:true});fs.writeFileSync(path.resolve('output/notes-editing/block-catalog-0.1.90.png'),(await window.webContents.capturePage()).toPNG());
  await fill('[aria-label="Search blocks"]','Database');
  await wait("document.querySelectorAll('.noteInsertCatalog button').length===1");
  window.showInactive();await pause(150);
  fs.mkdirSync(path.resolve('output/notes-editing'),{recursive:true});fs.writeFileSync(path.resolve('output/notes-editing/insert-menu-0.1.90.png'),(await window.webContents.capturePage()).toPNG());
  await run("document.querySelector('[aria-label=\"Search blocks\"]').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))");
  await wait("document.querySelector('[aria-label=\"Insert database\"]')");await click('[aria-label="Close database picker"]');
  await run("document.querySelector('.noteDocumentScroll').scrollTop=0");
  await click('[aria-label="Page design"]');await fill('[aria-label="Page icon"]','🌿');
  await textClick('.notePageDesignPanel button','Add cover');await wait("document.querySelector('.notePageCover')?.naturalWidth>0");
  await fill('[aria-label="Cover position"]','27');await pause(800);
  assert.equal(agent.notes.read(page.id).presentation.iconText,'🌿');assert.equal(agent.notes.read(page.id).presentation.coverPosition,27);
  await context('.noteProse > p');await menuAction('Blue background');
  assert.equal(await run("document.querySelector('.noteProse > p').dataset.blockTone"),'blue');
  await context('.noteProse > p');await menuAction('2 columns');
  await context('[data-type=column] p');await textClick('.noteColumnPresets button','1 : 3');
  assert.equal(await run("document.querySelector('[data-type=column]').getAttribute('data-column-width')"),'25');
  await fill('[aria-label="Column 1 width"]','40');
  assert.equal(await run("document.querySelector('[data-type=column]').getAttribute('data-column-width')"),'40');
  await run("document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}))");await pause(850);
  const designed=agent.notes.read(page.id);assert(JSON.stringify(designed.document).includes('"tone":"blue"'));assert(JSON.stringify(designed.document).includes('"width":40'));
  window.showInactive(); await pause(200); await run("document.querySelector('.noteDocumentScroll').scrollTop=100000"); await pause(150);
  fs.mkdirSync(path.resolve('output/playwright'), { recursive: true }); fs.writeFileSync(path.resolve('output/playwright/editor-ui.png'), (await window.webContents.capturePage()).toPNG());
  assert.deepEqual(errors, []); console.log('EDITOR_UI_OK: contextual tools, alignment, block move, columns preserve content, table rows/columns, durable picker/paste/drop images and real embedded database'); window.destroy(); await agent.close(); app.quit();
} catch (error) { console.error(error); await agent?.close(); app.exit(1); } });
