const assert = require('node:assert/strict');
const path = require('node:path');
const { app, BrowserWindow, ipcMain } = require('electron');
const pause = () => new Promise(resolve => setTimeout(resolve, 100));
app.whenReady().then(async () => {
  try {
    const sent = [];
    ipcMain.on('niwa-test-send', (_event, text) => sent.push(text));
    const window = new BrowserWindow({ show: false, webPreferences: { preload: path.join(__dirname, 'settings-ui-preload.cjs') } });
    await window.loadFile(path.resolve('dist/index.html'));
    await pause();
    await window.webContents.executeJavaScript(`document.querySelector('[data-section=niwa]').click()`);
    await pause();
    await window.webContents.executeJavaScript(`document.querySelector('[aria-label="Message Niwa"]').focus()`);
    await window.webContents.insertText('日本語');
    const enter = async (modifiers = []) => {
      window.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Return', modifiers });
      window.webContents.sendInputEvent({ type: 'char', keyCode: '\r', modifiers });
      window.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'Return', modifiers });
      await pause();
    };
    await enter(['shift']);
    await window.webContents.insertText('Drugi red');
    const value = () => window.webContents.executeJavaScript(`document.querySelector('[aria-label="Message Niwa"]').value`);
    assert.equal(await value(), '日本語\nDrugi red');
    assert.equal(sent.length, 0, 'Shift+Enter only inserts a newline');
    await window.webContents.executeJavaScript(`document.querySelector('[aria-label="Message Niwa"]').dispatchEvent(new KeyboardEvent('keydown', {key:'Enter', isComposing:true, bubbles:true}))`);
    assert.equal(sent.length, 0, 'IME confirmation does not send');
    await enter();
    assert.deepEqual(sent, ['日本語\nDrugi red']);
    assert.equal(await value(), '');
    const sendEvent = event => window.webContents.send('test-niwa-event', event);
    for (let index = 0; index < 120; index++) sendEvent({ type: 'message', id: String(index), role: 'assistant', content: `Message ${index}`, timestamp: index });
    await pause();
    assert.equal(await window.webContents.executeJavaScript("document.querySelectorAll('.niwaBubble').length"), 100, 'long chats mount only the newest page');
    await window.webContents.executeJavaScript("[...document.querySelectorAll('button')].find(button => button.textContent.includes('Load earlier')).click()");
    await pause();
    assert.equal(await window.webContents.executeJavaScript("document.querySelectorAll('.niwaBubble').length"), 120);
    for (let index = 0; index < 100; index++) sendEvent({ type: 'delta', id: 'stream', text: '語' });
    sendEvent({ type: 'busy', busy: false });
    await pause();
    assert((await window.webContents.executeJavaScript("document.querySelector('.niwaBubble:last-of-type').textContent")).includes('語'.repeat(100)), 'batched stream retains every delta');
    sendEvent({ type: 'message', id: 'stream', role: 'assistant', content: 'Completed 完了', timestamp: 121 });
    await pause();
    assert((await window.webContents.executeJavaScript("document.querySelector('.niwaBubble:last-of-type').textContent")).includes('Completed 完了'), 'final message replaces deltas');
    sendEvent({ type: 'delta', id: 'old', text: 'stale' });
    sendEvent({ type: 'conversation' });
    await pause();
    assert.equal(await window.webContents.executeJavaScript("document.querySelectorAll('.niwaBubble').length"), 0, 'pending deltas cannot leak into the next chat');
    console.log('NIWA_ENTER_SHIFT_ENTER_IME_OK');
    app.exit(0);
  } catch (error) { console.error(error); app.exit(1); }
});
