import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {formula,computedRows,queryRows,matches} from '../electron/notes/database-engine.mjs';
import {createNotesStore} from '../electron/notes-store.mjs';
import {readNotionDirectory,resolveAsset,exportedPage} from '../electron/notes/notion-import.mjs';
import {enrichNotionBundle} from '../electron/notes/notion-metadata.mjs';
const shortened = new Map([['1234'+'a'.repeat(24)+'5678',{id:'database'}]]);
assert.equal(exportedPage(shortened,'資料 1234-5678.csv').id,'database');
shortened.set('1234'+'b'.repeat(24)+'5678',{id:'other'});
assert.equal(exportedPage(shortened,'資料 1234-5678.csv'),undefined,'ambiguous shortened IDs must never point at the wrong database');
assert.equal(formula('if(prop("数") > 2, repeat("✓", prop("数")), "")',{'数':3}),'✓✓✓');
assert.equal(formula('prop("تاريخ").dateAdd(1, "months")',{'تاريخ':{start:'2026-01-01'}}),'2026-02-01T00:00:00.000Z');
assert.throws(()=>formula('prop("x").constructor("return globalThis")()',{}));
assert.throws(()=>formula('repeat("x", 1e9)',{}));
const child={id:'child',properties:[{id:'title',name:'名称',type:'title'},{id:'a',name:'数',type:'number'},{id:'b',name:'Double',type:'formula',expression:'prop("数") * 2'}],rows:[{id:'row',pageId:'page',values:{a:5}}],views:[{id:'all',name:'All',type:'table'}]};
const parent={id:'parent',properties:[{id:'title',name:'名称',type:'title'},{id:'r',name:'Связь',type:'relation',target:'child'},{id:'s',name:'Sum',type:'rollup',relation:'r',targetProperty:'b',aggregation:'sum'}],rows:[{id:'one',values:{r:['page']}}],views:[{id:'all',name:'All',type:'table'}]};
assert.equal(computedRows(parent,[child])[0].values.s,10);
child.properties[2].expression='prop("Double")';assert.match(computedRows(parent,[child])[0].errors.s,/Circular/);
child.properties[2].expression='';child.rows[0].values.b=42;assert.equal(computedRows(child)[0].values.b,42);assert.match(computedRows(child)[0].errors.b,/source is missing/);
assert.equal(matches({x:{start:null}},{property:'x',operator:'empty'}),true);
assert.equal(matches({x:[{name:'Име',id:'user://1'}]},{property:'x',operator:'contains',value:'user://1'}),true);
assert.equal(queryRows(child,{filter:{operator:'and',filters:[{property:'a',operator:'gt',value:4}]}}).length,1);
const directory=mkdtempSync(join(tmpdir(),'localflow-notion-')),source=join(directory,'export'),group=join(source,'Export','Workspace');mkdirSync(join(group,'親','資料'),{recursive:true});
const a='a'.repeat(32),b='b'.repeat(32),c='c'.repeat(32),hash='d'.repeat(32);
writeFileSync(join(group,`親 ${a}.html`),`<html><body><article><header><img class="page-cover-image" src="photo.png" style="object-position:center 79%"><div class="page-header-icon"><img src="photo.png"></div><h1 class="page-title">親</h1></header><div class="page-body"><div class="column-list"><div class="column" style="width:18.75%"><p>Left</p></div><div class="column" style="width:81.25%"><p>Right</p></div></div><h2>العربية</h2><script>bad()</script><a href="親/資料%20${b}.html">資料</a><img src="photo.png" onerror="bad()"><details><summary>Toggle</summary><p>Keep this text</p></details></div></article></body></html>`);
writeFileSync(join(group,'photo.png'),'fixture');writeFileSync(join(group,'親',`資料 ${b}.html`),`<html><body><h1 class="page-title">資料</h1><div class="page-body"></div></body></html>`);writeFileSync(join(group,'親',`資料 ${b}.csv`),'Name,数\n項目,5\n');writeFileSync(join(group,'親','資料',`項目 ${c}.html`),'<html><body><h1 class="page-title">項目</h1><table class="properties"><tr class="property-row-number"><th>数</th><td>5</td></tr></table><div class="page-body"><p>Note content</p></div></body></html>');
const bundle=readNotionDirectory(source,hash),page=bundle.items[0].children[0].children[0],db=page.children[0];
assert.equal(page.presentation.wide,true);assert.equal(page.presentation.coverPosition,79);assert(page.presentation.cover.startsWith('localflow-asset:'));assert(page.html.includes('data-column-width="18.75"'));assert(page.html.includes('data-column-width="81.25"'));
assert.equal(db.database.rows.length,1,'CSV and HTML refer to the same row');assert.equal(db.children[0].id,`notion-${c}`);assert(!page.html.includes('onerror'));assert(!page.html.includes('<script'));assert(page.content.includes(`localflow-note://notion-${b}`));assert(page.html.includes('Keep this text'));
enrichNotionBundle(bundle,{[b]:{states:[{url:'collection://one',schema:{Name:{name:'Name',type:'title'},数:{name:'数',type:'number'},式:{name:'式',type:'formula',codeUrl:'formulaCode://one/x'}}}],views:[{url:'view://table',type:'table',name:'Filtered',simpleFilters:[{filter:{property:'数',operator:'enum_is',value:{type:'exact',value:5}}}]}]}},{formulas:{'formulaCode://one/x':'prop("数") * 2'}});
assert.equal(computedRows(db.database)[0].values[db.database.properties.find(p=>p.type==='formula').id],10);
const store=createNotesStore(directory);const original=store.create({label:'Existing',content:'Do not lose'});store.importBundle(bundle);assert.equal(store.read(original.id).content,'Do not lose');assert(store.importBundle(bundle).alreadyImported);assert.equal(store.read(`notion-${c}`).content,'Note content');
const before=store.databaseRead(db.id),updated=store.databaseSave({...before,rows:before.rows.map(r=>({...r,values:{...r.values,[before.properties.find(p=>p.type==='title').id]:'Renamed'}}))});assert.equal(store.read(`notion-${c}`).label,'Renamed');assert.throws(()=>store.databaseSave(before),/changed elsewhere/);
store.databaseAddRow({id:db.id,label:'New',values:{p1:12}});assert.equal(store.databaseRead(db.id).rows.length,2);
const target=store.create({kind:'database',label:'Target'});let actionDb=store.databaseRead(db.id);const titleId=actionDb.properties.find(p=>p.type==='title').id;actionDb.properties.push({id:'button',name:'Create related record',type:'button',actions:[{type:'add_row',databaseId:target.id,values:{title:{kind:'property',property:titleId}}},{type:'edit_row',values:{p1:{kind:'value',value:99}}}]});actionDb=store.databaseSave(actionDb);store.databaseRunButton({id:db.id,rowId:actionDb.rows[0].id,propertyId:'button',revision:actionDb.revision});assert.equal(store.databaseRead(target.id).rows.length,1);assert.equal(store.databaseRead(db.id).rows[0].values.p1,99);assert.throws(()=>store.databaseRunButton({id:db.id,rowId:actionDb.rows[0].id,propertyId:'button',revision:actionDb.revision}),/changed/);
mkdirSync(join(directory,'notes','imports'),{recursive:true});writeFileSync(join(directory,'notes','imports','locations.json'),JSON.stringify({[hash]:source}));assert.equal(resolveAsset(join(directory,'notes'),`localflow-asset://${hash}/Export/Workspace/photo.png`),join(group,'photo.png'));assert.throws(()=>resolveAsset(join(directory,'notes'),`localflow-asset://${hash}/..%2F..%2Foutside.txt`));
console.log('NOTES_DATABASES_OK: Unicode formulas, recursive rollups, conditions, safe import, hierarchy, CSV deduplication, assets, persistence, revisions, idempotency');
