const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { app, BrowserWindow, ipcMain } = require('electron');
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'localflow-optimized-ui-'));
app.setPath('userData', directory);
fs.mkdirSync(path.join(directory, 'niwa'), { recursive: true });
fs.writeFileSync(path.join(directory, 'niwa', 'conversation.json'), JSON.stringify({ id: 'long-chat', projectId: directory, transcript: Array.from({ length: 1000 }, (_, index) => ({ id: `message-${index}`, role: 'user', content: `Message ${index} 日本語`, timestamp: index })) }));
app.whenReady().then(async () => {
  let stage = 'creating window';
  const watchdog = setTimeout(() => { console.error(`Optimized UI timed out: ${stage}`); app.exit(1); }, 30000);
  let agent;
  try {
    const { createNiwaAgent } = await import('../electron/niwa-agent.mjs');
    const window = new BrowserWindow({ width: 1440, height: 940, show: false, webPreferences: { sandbox: false, backgroundThrottling: false, additionalArguments: ['--workspace-check'], preload: path.join(__dirname, 'settings-ui-preload.cjs') } });
    const errors = [];
    const loadedScripts = new Set();
    await window.loadURL('about:blank');
    window.webContents.debugger.attach('1.3');
    window.webContents.debugger.on('message', (_event, method, value) => { if (method === 'Debugger.scriptParsed' && value.url.includes('/dist/assets/') && value.url.endsWith('.js')) loadedScripts.add(value.url); });
    stage = 'enabling debugger';
    await window.webContents.debugger.sendCommand('Debugger.enable');
    window.webContents.on('console-message', (_event, level, message) => { if (level >= 3) errors.push(message); });
    agent = createNiwaAgent({ directory, appRoot: path.resolve('.'), binary: () => '', speak: async () => {}, notify: event => window.webContents.send('test-niwa-event', event) });
    for (const method of ['list', 'read', 'importLegacy', 'create', 'save', 'remove']) ipcMain.handle(`workspace-notes-${method}`, (_event, value) => agent.notes[method](value));
    ipcMain.handle('workspace-snapshot', (_event, value) => agent.snapshot(value));
    ipcMain.handle('workspace-projects', () => agent.projects());
    stage = 'loading app';
    await window.loadFile(path.resolve('dist/index.html'));
    const run = script => window.webContents.executeJavaScript(script);
    const wait = async script => { stage = script; for (let i = 0; i < 100; i++) { if (await run(script)) return; await new Promise(resolve => setTimeout(resolve, 30)); } throw new Error(`Timed out: ${script}`); };
    await wait("document.querySelectorAll('.niwaBubble').length===100");
    assert.equal(loadedScripts.size, 1, 'Plaintext history does not load the syntax highlighter chunk');
    assert.equal(agent.snapshot().messages.length, 100);
    assert.equal(agent.snapshot().messageOffset, 900);
    assert.throws(() => agent.snapshot({ conversationId: 'stale-chat', before: 900 }), /changed/);
    assert.throws(() => agent.snapshot({ limit: 100000 }), /Invalid/);
    await run("[...document.querySelectorAll('button')].find(button=>button.textContent==='Load earlier messages').click()");
    await wait("document.querySelectorAll('.niwaBubble').length===200");
    assert.match(await run("document.querySelector('.niwaBubble').textContent"), /Message 800/);
    window.webContents.send('test-niwa-event', { type: 'delta', id: 'streaming-code', text: '```js\nconst world = 1;\n```' });
    await wait("document.querySelector('.niwaBubble.assistant pre')!==null");
    assert.equal(await run("document.querySelector('.niwaBubble.assistant .hljs-keyword')"), null, 'Streaming code avoids highlighting each token');
    window.webContents.send('test-niwa-event', { type: 'busy', busy: false });
    await wait("document.querySelector('.niwaBubble.assistant .hljs-keyword')!==null");
    assert.equal(loadedScripts.size, 2, 'Syntax highlighter is loaded only when completed code needs it');
    const diff = `diff --git a/large.ts b/large.ts\n--- a/large.ts\n+++ b/large.ts\n@@ -0,0 +1,50000 @@\n${Array.from({ length: 50000 }, (_, index) => `+日本語${index}`).join('\n')}\ndiff --git a/second.ts b/second.ts\n--- a/second.ts\n+++ b/second.ts\n@@ -0,0 +1,1 @@\n+second file\n`;
    window.webContents.send('test-niwa-event', { type: 'diff', diff });
    await wait("document.querySelectorAll('.diffFile').length===2 && document.querySelectorAll('.diffLine').length>0");
    const mounted = await run("document.querySelectorAll('.diffLine').length");
    assert(mounted <= 40, `Only viewport rows should mount, got ${mounted}`);
    assert.equal(await run("document.querySelectorAll('.diffFile')[1].querySelector('.diffCode')"), null, 'closed files do not mount code');
    await run("{ const input=document.querySelector('[aria-label=\"Find in large.ts\"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'日本語49999');input.dispatchEvent(new Event('input',{bubbles:true})); }");
    await wait("document.querySelector('.diffCode').textContent.includes('日本語49999')");
    await run("document.querySelector('[aria-label=\"Toggle split diff\"]').click()");
    await wait("document.querySelector('.diffPair') !== null && document.querySelector('.diffCode').textContent.includes('日本語49999')");
    assert(await run("document.querySelectorAll('.diffPair').length<=40"));
    await run("document.querySelectorAll('.diffFile')[1].querySelector('summary').click()");
    await wait("document.querySelectorAll('.diffFile')[1].querySelector('.diffCode')?.textContent.includes('second file')");
    await run("document.querySelector('.diffFile summary').click()");
    await wait("document.querySelector('.diffFile').querySelector('.diffCode')===null");
    await run("[...document.querySelectorAll('.changedFileRow')].find(button=>button.textContent.includes('large.ts')).click()");
    await wait("document.querySelector('.diffFilter').value==='large.ts' && document.querySelector('.diffFile[open] .diffCode')!==null");
    assert.equal(errors.length, 0, errors.join('\n'));
    console.log(JSON.stringify({ result: 'OPTIMIZED_UI_OK', messagesInStore: 1000, messagesPerSnapshot: 100, messagesAfterLoad: 200, diffRows: 50000, mountedUnifiedRows: mounted, splitSearchAndCollapsedFiles: true }));
  } catch (error) { console.error(error); process.exitCode = 1; }
  finally { stage = 'closing agent'; await agent?.close(); clearTimeout(watchdog); app.exit(process.exitCode || 0); }
});
