import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import codex from '../host/codex-client.cjs';
import { createNiwaAgent } from '../host/niwa-agent.mjs';
import { createNotesStore } from '../host/notes-store.mjs';

import { TestClient } from './agent-client-fixture.mjs';
const original = codex.CodexClient;
codex.CodexClient = TestClient;
const directory = mkdtempSync(join(tmpdir(), 'localflow-projects-'));
const options = { directory, appRoot: resolve('.'), binary: () => '', notify: () => {}, speak: async () => {} };
let agent = createNiwaAgent(options);
try {
  const md = '# Извештај\n\n## 日本語\n\n- [x] العربية\n\n| Name | Value |\n| --- | --- |\n| a | **b** |\n\n```ts\nconst value = 1;\n```';
  const notes = agent.notes;
  (await notes.importLegacy([{ id: 'inbox', kind: 'folder', label: 'Inbox', children: [{ id: 'old', kind: 'note', label: 'Old note', content: md }] }]));
  assert.equal((await notes.read('old')).content, md);
  const reopened = createNotesStore(directory);
  assert.equal(reopened.read('old').content,md); reopened.close();
  const before = (await notes.read('old'));
  (await notes.save({ ...before, content: `${md}\n\nNew paragraph` }));
  await assert.rejects(() => notes.save({ ...before, content: 'stale' }), /changed elsewhere/);
  const external = (await notes.read('old')); await notes.save({...external,content:'External editor'});
  await assert.rejects(() => notes.save(external), /changed elsewhere/);
  await assert.rejects(() => notes.create({ kind: 'note', label: 'bad', parentId: 'missing' }), /folder/);
  const invalid=createNotesStore(join(directory,'invalid-import'));
  try {assert.throws(()=>invalid.importLegacy([{id:'../outside',kind:'note',label:'bad',content:''}]),/Invalid/);}finally{invalid.close();}
  await notes.remove('old'); assert((await notes.trash()).some(item=>item.id==='old'));
  const removed=createNotesStore(directory);assert.equal(removed.list().items[0].children.length,0);removed.close();
  await notes.restore('old');assert.equal((await notes.read('old')).content,'External editor','Removed notes remain recoverable');
  await agent.connect();
  const homeThread = TestClient.current.threadId;
  const toolSpecs = TestClient.current.calls.find(call => call.method === 'thread/start').params.dynamicTools;
  assert(toolSpecs.some(tool => tool.name === 'notes_create'));
  TestClient.current.emit('request', { id: 99, method: 'item/tool/call', params: { threadId: homeThread, callId: 'n', tool: 'notes_create', arguments: { label: 'Voice report', content: md } } });
  for (let i = 0; !TestClient.current.response && i < 100; i++) await new Promise(resolve => setTimeout(resolve, 20));
  assert.equal(TestClient.current.response.result.success, true);
  assert((await notes.list()).items.some(item => item.label === 'Voice report'));
  TestClient.current.notify('item/completed', { item: { id: 'home-message', type: 'agentMessage', text: 'Niwa home' } });
  const projectPath = join(directory, 'project'), subPath = join(projectPath, '子目录'); mkdirSync(subPath, { recursive: true });
  const project = agent.addProject({ path: projectPath });
  const child = project;
  assert.throws(() => agent.addProject({ path: directory, parentId: project.id }), /subfolders/);
  agent.openFolder(child.id); const firstId = agent.projects().activeId;
  assert.equal(agent.snapshot().settings.cwd, projectPath);
  assert.equal(agent.snapshot().messages.length, 0);
  await agent.send('Prvi chat 日本語');
  assert.throws(() => agent.selectChat('niwa'), /Finish/);
  TestClient.current.notify('turn/diff/updated', { diff: 'first-diff' });
  TestClient.current.notify('turn/completed', { turn: { status: 'completed' } });
  const firstThread = TestClient.current.threadId;
  await agent.configure({ effort: 'high' });
  agent.newChat(child.id); assert.notEqual(agent.projects().activeId, firstId);
  await agent.connect(); assert.notEqual(TestClient.current.threadId, firstThread); assert.equal(agent.snapshot().diff, '');
  agent.selectChat(firstId); await agent.connect();
  assert.equal(TestClient.current.threadId, firstThread); assert.equal(agent.snapshot().settings.effort, 'high'); assert.equal(agent.snapshot().diff, 'first-diff');
  assert.equal(agent.snapshot().messages[0].content, 'Prvi chat 日本語');
  agent.selectChat('niwa'); await agent.connect(); assert.equal(TestClient.current.threadId, homeThread); assert.equal(agent.snapshot().messages[0].content, 'Niwa home');
  await agent.configure({ access: 'read' }); await agent.connect();
  TestClient.current.emit('request', { id: 100, method: 'item/tool/call', params: { threadId: TestClient.current.threadId, callId: 'n', tool: 'notes_create', arguments: { label: 'Forbidden', content: '' } } });
  await new Promise(resolve => setImmediate(resolve)); assert.equal(TestClient.current.response.result.success, false);
  agent.selectChat(firstId); await agent.close(); agent = createNiwaAgent(options);
  assert.equal(agent.projects().activeId, firstId); assert.equal(agent.snapshot().settings.cwd, projectPath); assert.equal(agent.snapshot().messages[0].content, 'Prvi chat 日本語');
  console.log('PROJECT_NOTES_OK: Markdown migration, disk persistence, revision conflicts, note tool parity, permissions, flat project validation, chat/thread isolation and restart');
} finally { await agent.close(); codex.CodexClient = original; }
