const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const { component } = require('../scripts/release-components.cjs');
const root = fs.mkdtempSync(path.resolve('runtime/release-check-'));
const source = path.join(root, 'runtime/mock/model.bin');
fs.mkdirSync(path.dirname(source), { recursive: true });
fs.writeFileSync(source, 'installed model');
const previous = path.join(root, 'installed/LocalFlow-0.2.2-Windows-x64');
fs.mkdirSync(previous, { recursive: true });
fs.writeFileSync(path.join(previous, 'LocalFlow.exe'), 'previous code');
const manifest = { version: '0.2.3', components: [component(root, previous, 'runtime/mock')] };
fs.writeFileSync(source, 'changed build source');
const model = path.join(previous, 'runtime/mock/model.bin');
assert.equal(fs.readFileSync(model, 'utf8'), 'installed model', 'Rebuilding cannot mutate a released component');
const update = path.join(root, 'update');
fs.mkdirSync(path.join(update, 'scripts'), { recursive: true });
fs.copyFileSync('scripts/update-localflow.ps1', path.join(update, 'scripts/update-localflow.ps1'));
fs.writeFileSync(path.join(update, 'LocalFlow.exe'), 'new code');
const manifestFile = path.join(update, 'runtime-components.json');
fs.writeFileSync(manifestFile, JSON.stringify(manifest));
const run = () => spawnSync('powershell.exe', ['-NoProfile', '-File', path.join(update, 'scripts/update-localflow.ps1'), '-From', previous], { windowsHide: true, encoding: 'utf8' });
const result = run();
assert.equal(result.status, 0, result.stderr);
const next = path.join(root, 'installed/LocalFlow-0.2.3-Windows-x64');
assert.equal(fs.readFileSync(path.join(next, 'LocalFlow.exe'), 'utf8'), 'new code');
assert.equal(fs.readFileSync(path.join(previous, 'LocalFlow.exe'), 'utf8'), 'previous code');
assert.equal(fs.statSync(path.join(next, 'runtime/mock/model.bin')).ino, fs.statSync(model).ino, 'Updates reuse installed model bytes');
assert.notEqual(run().status, 0, 'Never overwrite an existing release');
manifest.version = '0.2.4';
fs.writeFileSync(manifestFile, JSON.stringify(manifest));
fs.writeFileSync(model, 'corrupt installed model');
assert.notEqual(run().status, 0);
assert(!fs.existsSync(path.join(root, 'installed/LocalFlow-0.2.4-Windows-x64')), 'Verify hashes before creating the target');
console.log('RELEASE_COMPONENTS_UPDATE_OK: immutable releases, reused model, preserved previous code, overwrite and corruption refused');
fs.utimesSync(path.join(update, 'LocalFlow.exe'), 0, 0);
const zipped = spawnSync(path.resolve('runtime/python/python.exe'), ['scripts/zip-release.py', update], { windowsHide: true, encoding: 'utf8' });
assert.equal(zipped.status, 0, zipped.stderr);
const checked = spawnSync(path.resolve('runtime/python/python.exe'), ['-c', 'import sys,zipfile; z=zipfile.ZipFile(sys.argv[1]); assert z.testzip() is None; assert z.read("update/LocalFlow.exe")==b"new code"', update + '.zip'], { windowsHide: true, encoding: 'utf8' });
assert.equal(checked.status, 0, checked.stderr);
console.log('RELEASE_ZIP_TIMESTAMP_CRC_OK');
