const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { ensureShortcuts, normalizeShortcutBinding, readShortcuts, saveShortcut } = require('../electron/shortcuts.cjs');
fs.mkdirSync('runtime/shortcut-check', { recursive: true });
const directory = fs.mkdtempSync(path.resolve('runtime/shortcut-check/run-'));
assert.deepEqual(readShortcuts(directory).dictation.keys, [0x11, 0x10]);
assert.deepEqual(readShortcuts(directory)['niwa-agent'].keys, [0x11, 0x14]);
saveShortcut(directory, 'dictation', { keys: [5], label: 'Mouse Back' });
assert.deepEqual(readShortcuts(directory).dictation, { keys: [5], label: 'Mouse Back' });
assert.throws(() => saveShortcut(directory, 'niwa-agent', { keys: [5], label: 'Mouse Back' }), /already assigned/);
assert.throws(() => saveShortcut(directory, 'unknown', { keys: [65], label: 'A' }), /Unknown/);
assert.throws(() => normalizeShortcutBinding({ keys: [1], label: 'Left click' }), /not supported/);
fs.writeFileSync(path.join(directory, 'shortcuts.json'), JSON.stringify({ dictation: { keys: [5], label: 'Mouse Back' }, 'hermes:old': { keys: [17,20], label: 'Ctrl + Caps Lock' } }));
const migrated = ensureShortcuts(directory);
assert.equal(migrated['hermes:old'], undefined);
assert.equal(migrated.dictation.label, 'Mouse Back');
assert.equal(migrated['niwa-agent'].label, 'Ctrl + Caps Lock');
console.log('SHORTCUT_CONFIG_OK');
