const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');
const { app, BrowserWindow, ipcMain } = require('electron');
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'localflow-workspace-'));
app.setPath('userData', directory);
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
app.whenReady().then(async () => {
  let agent;
  try {
    const { TestClient } = await import('./agent-client-fixture.mjs');
    require('../electron/codex-client.cjs').CodexClient = TestClient;
    const { createNiwaAgent } = await import('../electron/niwa-agent.mjs');
    const window = new BrowserWindow({ width: 1440, height: 940, show: true, backgroundColor: '#10151d', webPreferences: { sandbox: false, backgroundThrottling: false, additionalArguments: ['--workspace-check'], preload: path.join(__dirname, 'settings-ui-preload.cjs') } });
    const errors = [];
    ipcMain.on('niwa-test-send', (_event, text) => { window.lastSentText = text; });
    window.webContents.on('console-message', (_event, level, message) => { if (level >= 3) { errors.push(message); console.error('RENDERER',message); } });
    agent = createNiwaAgent({ directory, appRoot: path.resolve('.'), binary: () => '', speak: async () => {}, notify: event => window.webContents.send('test-niwa-event', event) });
    for (const method of ['list', 'read', 'importLegacy', 'create', 'save', 'remove']) ipcMain.handle(`workspace-notes-${method}`, (_event, value) => agent.notes[method](value));
    for (const [channel, method] of Object.entries({ snapshot: 'snapshot', projects: 'projects', 'open-folder': 'openFolder', 'new-chat': 'newChat', 'select-chat': 'selectChat', 'rename-chat': 'renameChat', 'manage-project': 'manageProject', connect: 'connect', configure: 'configure', 'undo-changes': 'undoChanges' })) ipcMain.handle(`workspace-${channel}`, (_event, value) => agent[method](value));
    const projectPath = path.join(directory, 'LocalFlow'), subPath = path.join(projectPath, 'src'); fs.mkdirSync(subPath, { recursive: true });
    ipcMain.handle('workspace-add-project', (_event, parentId) => agent.addProject({ path: parentId ? subPath : projectPath, parentId }));
    await window.loadFile(path.resolve('dist/index.html'));
    const run = script => window.webContents.executeJavaScript(script).catch(error => { throw new Error(`${error.message}\n${script}`); });
    await run("window.addEventListener('error',event=>console.error(event.error?.stack))");
    const click = selector => run(`document.querySelector(${JSON.stringify(selector)}).click()`);
    const waitFor = async script => { for (let i = 0; i < 60; i++) { if (await run(script)) return; await pause(50); } console.error(await run("document.querySelector('.noteWorkspace')?.outerHTML.slice(0,3500)")); throw new Error(`Timed out: ${script}`); };
    const fill = (selector, value, element = 'HTMLInputElement') => run(`{ const input=document.querySelector(${JSON.stringify(selector)}); Object.getOwnPropertyDescriptor(${element}.prototype,'value').set.call(input,${JSON.stringify(value)}); input.dispatchEvent(new Event('input',{bubbles:true})); }`);
    await waitFor("document.querySelector('.projectsTreePane') !== null");
    assert.deepEqual(await run("[...document.querySelectorAll('.navList button')].map(b=>b.textContent)"), ['Agents','Notes']);
    assert(await run("document.querySelector('.profilePopover [data-section=settings]') !== null"), 'Settings lives in the profile menu');
    assert.equal(await run("document.querySelector('.notesTreePane')"), null);
    assert.equal(await run("getComputedStyle(document.querySelector('.sidebar')).backgroundColor"), 'rgba(0, 0, 0, 0.24)');
    assert(await run("document.querySelector('.brand').getBoundingClientRect().top <= 14"), 'Dark glass branding sits in the top corner');
    assert(await run("(() => { const r=document.querySelector('.profileTrigger').getBoundingClientRect();return Math.abs(r.left-(innerHeight-r.bottom))<1; })()"), 'Profile has equal left and bottom spacing');
    assert.equal(await run("getComputedStyle(document.querySelector('.appShell')).borderRadius"), '0px');
    const panes = await run(`(() => {
      const chat = document.querySelector('.niwaToolbar'), diff = document.querySelector('.agentDiff > header');
      return { chatBottom: chat.getBoundingClientRect().bottom, diffBottom: diff.getBoundingClientRect().bottom,
        chat: getComputedStyle(chat).backgroundColor,
        diff: getComputedStyle(document.querySelector('.agentDiff')).backgroundColor,
        workspace: getComputedStyle(document.querySelector('.workspace')).backgroundColor };
    })()`);
    assert.equal(panes.chatBottom, panes.diffBottom, 'Chat and Changes header dividers align');
    assert.equal(panes.chat, panes.workspace, 'Chat uses the titlebar background');
    assert.equal(panes.diff, panes.workspace, 'Changes uses the same background');
    await run("document.body.style.backgroundColor='#ff00ff'");
    await run("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
    await pause(300);
    const floating = await run(`(() => {
      const c=document.querySelector('.niwaComposer').getBoundingClientRect(), t=document.querySelector('.niwaTranscript').getBoundingClientRect();
      return { x: c.left+c.width*.6, y: c.top+25, feedBottom:t.bottom, composerBottom:c.bottom };
    })()`);
    assert(floating.feedBottom > floating.composerBottom, 'The feed extends behind the floating composer');
    const pixel = async () => { const shot=await window.webContents.capturePage(), bytes=shot.toBitmap(), offset=(Math.floor(floating.y)*shot.getSize().width+Math.floor(floating.x))*4;return [...bytes.subarray(offset,offset+3)]; };
    const plain = await pixel();
    assert(plain.every(value=>value<40), 'The desktop backdrop does not show through the composer');
    await run(`(() => {
      const t=document.querySelector('.niwaTranscript');t.style.position='relative';
      const r=t.getBoundingClientRect(), marker=document.createElement('div');marker.id='glass-feed-check';
      marker.style.cssText='position:absolute;width:180px;height:100px;background:rgb(220,100,40);left:'+(${floating.x}-r.left-90)+'px;top:'+(${floating.y}-r.top+t.scrollTop-50)+'px';
      t.append(marker);
    })()`);
    await run("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))"); await pause(300);
    const through = await pixel();
    assert(through[2]>plain[2]+40 && through[2]<220, 'Feed content shows through the tinted glass');
    await run("document.querySelector('#glass-feed-check').style.top='0px'");
    await run("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))"); await pause(300);
    assert.deepEqual(await pixel(), plain, 'Moving content away changes the backdrop while the composer stays fixed');
    await run("document.querySelector('#glass-feed-check').remove();document.querySelector('.niwaTranscript').style.removeProperty('position');document.body.style.removeProperty('background-color')");
    await click('[aria-label="Add project"]');
    await waitFor("document.querySelectorAll('.projectChat').length === 1");
    const firstChat = agent.projects().activeId;
    assert(await run(`(() => {
      const project=document.querySelector('.projectFolder > summary.selected'), chat=document.querySelector('.projectChat.selected');
      const p=project.getBoundingClientRect(), c=chat.getBoundingClientRect(), tree=document.querySelector('.projectTree').getBoundingClientRect();
      return p.width===tree.width && c.left-p.left===14 && c.right===p.right && getComputedStyle(project).borderRadius==='6px';
    })()`), 'Project highlight spans the full row; chat is inset with the same right edge');
    assert.equal(await run("document.querySelectorAll('[aria-label^=\"Add subfolder\"]').length"), 0);
    assert.equal(agent.snapshot().settings.cwd, projectPath);
    await click('[aria-label="New chat in LocalFlow"]');
    await waitFor("document.querySelectorAll('.projectChat').length === 2");
    const currentChat = agent.projects().activeId;
    assert.notEqual(currentChat, firstChat);
    await click('.projectChat.selected [title="Archive"]');
    await waitFor("document.querySelectorAll('.projectChat').length === 1");
    assert.equal(agent.projects().activeId, 'niwa');
    await click('[aria-label="Show archived projects and chats"]');
    await waitFor("document.querySelector('.projectChat [title=Restore]') !== null");
    await click('.projectChat [title="Restore"]');
    await click('[aria-label="Show archived projects and chats"]');
    await waitFor("document.querySelectorAll('.projectChat').length === 2");
    await click('.projectFolder > summary [title="Archive"]');
    await waitFor("document.querySelectorAll('.projectFolder').length === 0");
    await click('[aria-label="Show archived projects and chats"]');
    await waitFor("document.querySelector('.projectFolder > summary [title=Restore]') !== null");
    await click('.projectFolder > summary [title="Restore"]');
    await click('[aria-label="Show archived projects and chats"]');
    await agent.selectChat(currentChat);
    await pause(100);
    await click('[aria-label="New chat in LocalFlow"]');
    await waitFor("document.querySelectorAll('.projectChat').length === 3");
    await click('.projectChat.selected [title="Delete chat"]');
    await waitFor("document.querySelectorAll('.projectChat').length === 2");
    await agent.selectChat(currentChat);
    await click('.codingControls button'); await waitFor("document.querySelector('[aria-label=\"Coding model\"]').textContent.includes('Test model')");
    await run("{const e=document.querySelector('[aria-label=\"Reasoning effort\"]');e.value='high';e.dispatchEvent(new Event('change',{bubbles:true}));}");
    await pause(100); assert.equal(agent.snapshot().settings.effort, 'high');
    await agent.connect();
    const markdown = '# Workspace report\n\nThe chat and code changes share one window.\n\n- [x] Separate project chats\n- [ ] Review the result\n\n| Language | Status |\n| --- | --- |\n| Српски | Ready |\n| 日本語 | Ready |\n\n```ts\nconst workspace = "src";\n```';
    TestClient.current.notify('turn/started', { turn: { id: 'ui-turn' } });
    TestClient.current.notify('item/completed', { item: { type: 'agentMessage', id: 'answer', text: markdown } });
    TestClient.current.notify('turn/diff/updated', { diff: 'diff --git a/src/navigation.ts b/src/navigation.ts\n--- a/src/navigation.ts\n+++ b/src/navigation.ts\n@@ -10,3 +10,3 @@\n-const view = "Notes";\n+const view = "Agents";\n const folders = true;\n const title = "日本語 · العربية";' });
    TestClient.current.notify('item/completed', { item: { type: 'commandExecution', id: 'build', command: 'npm run build ' + 'long-unbroken-command'.repeat(80), aggregatedOutput: 'Build completed successfully.', status: 'completed' } });
    TestClient.current.notify('turn/completed', { turn: { id: 'ui-turn', status: 'completed' } });
    await waitFor("document.querySelector('.niwaTranscript table') !== null && document.querySelector('.diffCode')?.textContent.includes('日本語')");
    await waitFor("document.querySelector('.chatWork > summary').textContent.includes('Worked for')");
    assert(await run("document.querySelector('.chatChanges').textContent.includes('Edited 1 file')"));
    assert(await run("document.querySelector('.niwaComposer .codingControls') !== null && document.querySelector('.niwaComposer .niwaTalk') !== null"));
    await click('[aria-label="Add files"]'); await waitFor("document.querySelector('.chatAttachments')!==null");
    await fill('.niwaComposer textarea', 'Review this file', 'HTMLTextAreaElement'); await pause(80); await click('[aria-label="Send message"]'); await pause(80);
    assert(window.lastSentText.includes('日本語/readme.md')); assert(window.lastSentText.includes('Review this file'));
    assert(await run("document.querySelector('.messageCode .hljs-keyword') !== null"));
    assert(await run("document.querySelector('.lineNumber').textContent === '' && [...document.querySelectorAll('.lineNumber')].some(e=>e.textContent==='10')"));
    await click('[aria-label="Toggle split diff"]'); await pause(100); assert(await run("document.querySelectorAll('.diffPair').length > 0"));
    await click('[aria-label="Toggle split diff"]');
    const output = path.resolve('output/playwright'); fs.mkdirSync(output, { recursive: true });
    await pause(100); fs.writeFileSync(path.join(output,'agents.png'),(await window.webContents.capturePage()).toPNG());
    // Reference state: match the supplied Codex screenshot without changing real user data.
    const referenceDiff = ['electron/notes-store.mjs','electron/project-store.mjs','src/components/MarkdownContent.tsx','src/components/NotesPage.tsx','src/components/NiwaAgent.tsx','src/styles/chat.css','src/lib/niwa.ts'].map((name,index) => {
      const count=[74,41,20,21,20,20,20][index];
      return `diff --git a/${name} b/${name}\n--- a/${name}\n+++ b/${name}\n@@ -1,${index===0?1:0} +1,${count} @@\n${index===0?'-previous line\n':''}${Array.from({length:count},(_,n)=>'+line '+n).join('\n')}\n`;
    }).join('');
    const referenceText = 'Aktivna je **0.1.82**, izbildovana i pokrenuta.\n\n- **Agents:** projekti, podfolderi i zasebni chatovi; izabrani folder određuje workspace. Niwa ostaje glavna konverzacija.\n- **Chat/diff:** Markdown, kod, tabele, aktivnosti, brojevi redova i split prikaz.\n- **Coding agent:** vidljivi model, reasoning i dozvole.\n- **Notes:** naslovi, liste, checkliste, tabele, kod i automatsko Markdown čuvanje. Niwa koristi iste beleške preko svojih alata.\n\nPostojeće beleške su sačuvane. Prošli su build, UI testovi, čuvanje i provere mikrofona. Aplikacija je otvorena za feedback.';
    window.webContents.send('test-niwa-event',{type:'message',id:'reference-user',role:'user',content:'stvari koje bi ai agent mogao da upotrebi kada sastavlja ful notes izveštaj ili listu iz userovog audijo imputa',timestamp:Date.now()});
    window.webContents.send('test-niwa-event',{type:'message',id:'answer',role:'assistant',content:referenceText,timestamp:Date.now(),work:{startedAt:Date.now()-1950000,completedAt:Date.now(),activities:[{id:'long',title:'pwsh.exe '+ 'very-long-command'.repeat(150),content:'Completed',status:'completed'}],diff:referenceDiff}});
    window.webContents.send('test-niwa-event',{type:'diff',diff:referenceDiff});
    await click('[aria-label="Close changes"]');
    window.setContentSize(950,842);
    await run("{ const style=document.createElement('style');style.id='reference-crop';style.textContent='.sidebar{display:none!important}.appShell{grid-template-columns:1fr!important}.workspaceHeader{display:none!important}.workspace{grid-template-rows:minmax(0,1fr)!important}';document.head.append(style); }");
    await pause(200);
    assert.equal(await run("document.querySelectorAll('.changedFileRow').length"),3);
    await click('.showMoreFiles'); await pause(80); assert.equal(await run("document.querySelectorAll('.changedFileRow').length"),7); await click('.showMoreFiles');
    await click('.chatWork > summary'); await pause(80);
    assert(await run("document.querySelector('.niwaTranscript').scrollWidth <= document.querySelector('.niwaTranscript').clientWidth+1"),'expanded shell commands stay within the chat');
    await click('.chatWork > summary');
    await run("document.querySelector('.niwaTranscript').scrollTop=30"); await pause(150);
    fs.writeFileSync(path.join(output,'chat-reference.png'),(await window.webContents.capturePage()).toPNG());
    await click('.changedFileRow'); await pause(80); assert(await run("document.querySelector('.diffFilter').value === 'electron/notes-store.mjs'"));
    await run("document.querySelector('#reference-crop').remove()");window.setSize(1440,940);
    if (process.argv.includes('--chat-only')) {
      await fill('.niwaComposer textarea', Array(12).fill('A longer message').join('\n'), 'HTMLTextAreaElement'); await pause(200);
      assert(await run("parseFloat(getComputedStyle(document.querySelector('.niwaTranscript')).paddingBottom) >= document.querySelector('.niwaChatFooter').getBoundingClientRect().height"), 'The feed reserves enough tail space when the floating input grows');
      assert.equal(errors.length, 0);
      console.log('FLOATING_CHAT_OK: feed visible through glass, desktop hidden, input grows, send and attachment controls work');
      window.destroy(); app.quit(); return;
    }
    window.webContents.send('test-niwa-event',{type:'conversation'});await pause(200);
    await click('[aria-label="Save to Notes"]'); await pause(200);
    assert(agent.notes.list().items.some(item=>item.kind==='note'));
    await click('.navList [data-section="notes"]');
    await waitFor("document.querySelector('.notesTreePane') !== null");
    assert.equal(await run("document.querySelector('.projectsTreePane')"), null);
    await run("[...document.querySelectorAll('.sidebar [role=treeitem]')].find(e=>e.textContent.includes('Niwa')).click()");
    await waitFor("document.querySelector('.noteProse table') !== null");
    assert(await run("document.querySelector('.noteProse h1').textContent === 'Workspace report'"));
    assert(await run("document.querySelectorAll('.noteProse input[type=checkbox]').length === 2"));
    await click('[aria-label="Editor options"]');
    await click('.noteContextMenu [data-action=more]');
    await click('.noteActionFlyout [data-action=source]'); await pause(100);
    const updated = markdown + '\n\n## Voice notes\n\n**Bold**, *italic*, and a paragraph in العربية.';
    await fill('.noteMarkdownSource', updated, 'HTMLTextAreaElement');
    await waitFor("document.querySelector('.noteEditorHeader span').textContent.includes('Saved')");
    const noteId = agent.notes.list().items.find(item=>item.kind==='note').id;
    assert.equal(agent.notes.read(noteId).content, updated);
    assert.equal(fs.readFileSync(agent.notes.read(noteId).path, 'utf8'), updated);
    await click('.noteSourceToggle'); await pause(150);
    assert(await run("document.querySelector('.noteProse h2').textContent === 'Voice notes'"));
    await run("document.querySelector('.noteProse table td').scrollIntoView({block:'center'})");
    await pause(50);
    // Select inside a table with a real mouse event for Tiptap's native selection handling.
    const cell = await run("(()=>{const r=document.querySelector('.noteProse td').getBoundingClientRect();return {x:Math.round(r.x+12),y:Math.round(r.y+12)}})()");
    window.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...cell}); window.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...cell});
    await pause(80);
    await click('[aria-label="Editor options"]');
    await waitFor("document.querySelector('.noteContextMenu [data-action=table]') !== null");
    await click('.noteContextMenu [data-action=table]');
    const rowCount=await run("document.querySelectorAll('.noteProse tr').length");
    await click('.noteActionFlyout [data-action=table-1]'); await pause(800);
    assert.equal(await run("document.querySelectorAll('.noteProse tr').length"),rowCount+1);
    fs.writeFileSync(path.join(output,'notes.png'),(await window.webContents.capturePage()).toPNG());
    // An agent update arrives in the same editor without reloading the app.
    const current=agent.notes.read(noteId); agent.notes.save({...current,document:undefined,html:undefined,content:current.content+'\n\n### Agent update\n\nSynced from Niwa.'});
    await waitFor("document.querySelector('.noteProse').textContent.includes('Synced from Niwa.')");
    await window.reload(); await pause(450); await click('.navList [data-section="notes"]');
    await waitFor("document.querySelector('.noteProse')?.textContent.includes('Synced from Niwa.')");
    await click('.navList [data-section="niwa"]'); await pause(100);
    assert.equal(agent.projects().activeId,currentChat); assert(await run("document.querySelector('.niwaTranscript table')!==null"));
    await click('.niwaHome'); await pause(150); assert.equal(agent.projects().activeId,'niwa'); assert.equal(agent.snapshot().messages.length,0);
    await click('.profileTrigger'); await pause(250); assert(await run("document.querySelector('#profile-menu').matches(':popover-open')"));
    assert(await run("(() => {const icon=document.querySelector('.profileTrigger').getBoundingClientRect(), menu=document.querySelector('#profile-menu').getBoundingClientRect();return icon.width===28 && icon.width===document.querySelector('.brandLogo').getBoundingClientRect().width && Math.abs(menu.left-icon.left)<1 && Math.abs(menu.bottom-icon.bottom)<1;})()"), 'Profile menu covers the icon at the same corner');
    await click('.profileTrigger');
    window.setSize(1920, 1000); await pause(150);
    const paneWidth = selector => run(`document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect().width`);
    const dragDivider = async (label, delta) => {
      window.focus(); window.webContents.focus(); await pause(100);
      const point = await run(`(() => { const r = document.querySelector('[aria-label="${label}"]').getBoundingClientRect(); return { x: Math.round(r.x + r.width / 2), y: Math.round(r.y + 80) }; })()`);
      window.webContents.sendInputEvent({ type: 'mouseMove', ...point });
      window.webContents.sendInputEvent({ type: 'mouseDown', button: 'left', clickCount: 1, ...point }); await pause(30);
      window.webContents.sendInputEvent({ type: 'mouseMove', button: 'left', modifiers: ['leftButtonDown'], x: point.x + delta, y: point.y }); await pause(80);
      window.webContents.sendInputEvent({ type: 'mouseUp', button: 'left', clickCount: 1, x: point.x + delta, y: point.y }); await pause(100);
    };
    const sidebarBefore = await paneWidth('.sidebar');
    await dragDivider('Resize folders', 80);
    assert(Math.abs(await paneWidth('.sidebar') - sidebarBefore - 80) < 2, `left boundary resizes folders: ${sidebarBefore} -> ${await paneWidth('.sidebar')}; ${await run("document.querySelector('.appShell').getAttribute('style')")}`);
    const diffBefore = await paneWidth('.agentDiff');
    await dragDivider('Resize changes', -100);
    assert(Math.abs(await paneWidth('.agentDiff') - diffBefore - 100) < 2, 'right boundary resizes changes');
    const savedWidths = [await paneWidth('.sidebar'), await paneWidth('.agentDiff')];
    await window.reload(); await waitFor("document.querySelector('.projectsTreePane') !== null"); await pause(150);
    assert(Math.abs(await paneWidth('.sidebar') - savedWidths[0]) < 2, 'folder width survives restart');
    assert(Math.abs(await paneWidth('.agentDiff') - savedWidths[1]) < 2, 'diff width survives restart');
    await run("document.querySelector('[aria-label=\"Resize changes\"]').focus()");
    window.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Right' }); window.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'Right' }); await pause(100);
    assert(Math.abs(await paneWidth('.agentDiff') - savedWidths[1] + 10) < 2, 'keyboard moves the divider in the same direction');
    fs.writeFileSync(path.join(output, 'resized-panes.png'), (await window.webContents.capturePage()).toPNG());
    await click('[aria-label="Close changes"]'); await pause(100);
    const column = await run(`(() => { const c = document.querySelector('.niwaComposer').getBoundingClientRect(); const p = document.querySelector('.niwaConversation').getBoundingClientRect(); const t = document.querySelector('.niwaTranscript'); const s = getComputedStyle(t); return { width: c.width, center: c.x + c.width / 2, parentCenter: p.x + p.width / 2, textWidth: t.clientWidth - parseFloat(s.paddingLeft) - parseFloat(s.paddingRight) }; })()`);
    assert.equal(column.width, 736, 'composer stays readable on a wide display');
    assert(Math.abs(column.center - column.parentCenter) < 1, 'composer is centered in the chat');
    assert(column.textWidth <= 737, 'transcript uses the same readable column');
    fs.writeFileSync(path.join(output, 'centered-chat.png'), (await window.webContents.capturePage()).toPNG());
    await click('[aria-label="Toggle changes"]'); await pause(100);
    for (const width of [1440,900,680,390]) { window.setSize(width,900); await pause(100); assert(await run("document.querySelector('.agentDiff').getBoundingClientRect().right <= innerWidth")); }
    await click('[aria-label="Close changes"]'); await pause(100); assert(await run("document.querySelector('.niwaComposer').getBoundingClientRect().right <= innerWidth"));
    assert(await run("(() => { const t=document.querySelector('.niwaTranscript'); return t.scrollWidth<=t.clientWidth+1; })()"), 'Long activity commands must not widen the chat');
    assert.equal(errors.length,0,errors.join('\n'));
    console.log('WORKSPACE_UI_OK: real stores, flat projects/chats, archive/restore/delete, models, Markdown/code/table/task rendering, diff numbers/split, note tools, editor autosave, table editing, external sync, restart, responsive layout');
    await agent.close(); app.quit();
  } catch(error) { console.error(error); await agent?.close(); app.exit(1); }
});
