import type { Condition, Property } from '../../lib/database';
export function Conditions({ value, properties, onChange, depth = 0 }: { value: Condition; properties: Property[]; onChange: (next: Condition) => void; depth?: number }) {
  const rule = (): Condition => ({ property: properties[0]?.id, operator: 'is', value: '' });
  if (value.filters) return <div className="databaseConditions"><select aria-label="Condition group" value={value.operator} onChange={e => onChange({ ...value, operator: e.target.value, value:e.target.value==='relative_date'?{value:'this',unit:'week'}:value.value })}><option value="and">All conditions</option><option value="or">Any condition</option></select>{value.filters.map((filter, index) => <div className="conditionEntry" key={index}><Conditions value={filter} properties={properties} depth={depth + 1} onChange={next => onChange({ ...value, filters: value.filters!.map((f, i) => i === index ? next : f) })} /><button aria-label="Remove condition" onClick={() => onChange({ ...value, filters: value.filters!.filter((_, i) => i !== index) })}>×</button></div>)}<button onClick={() => onChange({ ...value, filters: [...value.filters!, rule()] })}>+ Condition</button>{depth < 6 && <button onClick={() => onChange({ ...value, filters: [...value.filters!, { operator: 'or', filters: [rule()] }] })}>+ Group</button>}</div>;
  const property = properties.find(p => p.id === value.property);
  return <div className="conditionRule"><select aria-label="Condition property" value={value.property || ''} onChange={e => onChange({ ...value, property: e.target.value, value: '' })}>{properties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="Condition operator" value={value.operator} onChange={e => onChange({ ...value, operator: e.target.value, value:e.target.value==='relative_date'?{value:'this',unit:'week'}:value.value })}>{[['is','Is'],['is_not','Is not'],['contains','Contains'],['not_contains','Does not contain'],['empty','Is empty'],['not_empty','Is not empty'],['gt','Greater than'],['gte','At least'],['lt','Less than'],['lte','At most'],['before','Before'],['after','After'],['relative_date','Relative date']].map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select>{!['empty','not_empty'].includes(value.operator) && (value.operator==='relative_date' ? <RelativeDate value={value.value} change={next=>onChange({...value,value:next})}/> : property?.type === 'checkbox' ? <select aria-label="Condition value" value={String(value.value || false)} onChange={e => onChange({ ...value, value: e.target.value === 'true' })}><option value="true">Checked</option><option value="false">Unchecked</option></select> : <input aria-label="Condition value" type={property?.type === 'number' ? 'number' : property?.type === 'date' ? 'date' : 'text'} value={String(value.value ?? '')} onChange={e => onChange({ ...value, value: property?.type === 'number' && e.target.value ? Number(e.target.value) : e.target.value })} />)}</div>;
}

function RelativeDate({value,change}:{value:unknown;change:(next:unknown)=>void}) {
  const date=(value&&typeof value==='object'?value:{value:'this',unit:'week'}) as {value:string;unit:string;count?:number;direction?:string};
  return <><select aria-label="Relative date range" value={date.value} onChange={e=>change({...date,value:e.target.value,direction:'past',count:7})}><option value="this">This</option><option value="custom">Custom range</option></select>{date.value==='custom'&&<><select aria-label="Relative date direction" value={date.direction||'past'} onChange={e=>change({...date,direction:e.target.value})}><option value="past">Past</option><option value="future">Next</option></select><input aria-label="Relative date count" type="number" min="1" max="36500" value={date.count||1} onChange={e=>change({...date,count:Math.max(1,Number(e.target.value))})}/></>}<select aria-label="Relative date unit" value={date.unit} onChange={e=>change({...date,unit:e.target.value})}>{['day','week','month','year'].map(unit=><option key={unit} value={unit}>{unit}</option>)}</select></>;
}
