import { useEffect, useMemo, useRef, useState } from 'react';
import { Database, Plus, ArrowUpRight, MoreHorizontal, Search } from 'lucide-react';
import type { NotesDatabase, DatabaseView, DatabaseRow, Property, DatabasePatch, DatabasePageAction } from '../../lib/database';
import type { NoteNode } from '../../lib/workspace';
import { displayValue, matches } from '../../../host/notes/database-engine.mjs';
import { DatabaseForm } from './DatabaseForm';
import { TimelineView } from './TimelineView';
import { Conditions } from './Conditions';
import { DatabaseTable } from './DatabaseTable';
import { DatabaseMenu } from './DatabaseMenu';
import '../../styles/database-editing.css';
import { PropertyEditor } from './PropertyEditor';
const flatten = (items: NoteNode[]): NoteNode[] => items.flatMap(item => [item, ...flatten(item.children || [])]);
export function DatabasePage({ id, label, open, embedded = false }: { id: string; label: string; open: (id: string) => void; embedded?: boolean }) {
  const scrollArea=useRef<HTMLDivElement>(null);
  const [destinations,setDestinations]=useState<NoteNode[]>([]);
  const [database, setDatabase] = useState<NotesDatabase | null>(null), [databases, setDatabases] = useState<NotesDatabase[]>([]);
  const relatedIds = useRef<string[]>([id]);
  const [viewId, setViewId] = useState(''), [editingView, setEditingView] = useState<DatabaseView | null>(null), [property, setProperty] = useState<Property | null>(null);
  const [error, setError] = useState(''), [pending, setPending] = useState(false), [search, setSearch] = useState(''), [offset, setOffset] = useState(0);
  const [rows, setRows] = useState<DatabaseRow[]>([]), [total, setTotal] = useState(0), [loading, setLoading] = useState(true);
  const [loadedKey, setLoadedKey] = useState(''), [pageOffset, setPageOffset] = useState(0);
  const [earliestDate, setEarliestDate] = useState<string>();
  const [queryError, setQueryError] = useState('');
  const [neighbors, setNeighbors] = useState<Record<string, {before?:string;after?:string}>>({});
  const loadSequence = useRef(0);
  const [confirmation,setConfirmation]=useState<{message:string;action:()=>void}|null>(null);
  const [menu,setMenu]=useState<{x:number;y:number;row?:DatabaseRow;property?:Property;view?:DatabaseView;more?:boolean}|null>(null), [showSearch,setShowSearch]=useState(false), [insertAt,setInsertAt]=useState<{id:string;after:boolean}|null>(null);
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const monthKey = `${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}`;
  const request = useRef({ id, viewId, search, offset, month: monthKey }); request.current = { id, viewId, search, offset, month: monthKey };
  const busy = pending || loading || loadedKey !== JSON.stringify(request.current);
  const changeMonth = (month: Date) => { setMonth(month); setOffset(0); };
  const load = async () => {
    const sequence = ++loadSequence.current, value = request.current, key = JSON.stringify(value); setLoading(true);
    try {
      const result = await window.localflow.notesDatabasePage(value);
      if (sequence !== loadSequence.current || key !== JSON.stringify(request.current)) return;
      setNeighbors(result.neighbors || {});
      relatedIds.current = result.dependencies || [id];
      setDatabase(result.database); setRows(result.rows); setDatabases(result.related); setTotal(result.total); setOffset(result.offset); setPageOffset(result.offset); setLoadedKey(key); setEarliestDate(result.earliestDate); setQueryError(result.queryError || ''); setError('');
    } catch (error) { if (sequence === loadSequence.current && key === JSON.stringify(request.current)) { setError(String(error)); setLoadedKey(key); }
    } finally { if (sequence === loadSequence.current) setLoading(false); }
  };
  useEffect(() => { const timer = setTimeout(() => void load().catch(e => setError(String(e))), search ? 150 : 0); return () => { clearTimeout(timer); loadSequence.current++; }; }, [id, viewId, search, offset, monthKey]);
  useEffect(()=>{let timer:ReturnType<typeof setTimeout>;const off=window.localflow.onNiwaEvent(event=>{if(event.type==='notes-changed'&&(!event.ids?.length||event.ids.some(id=>relatedIds.current.includes(id)))){clearTimeout(timer);timer=setTimeout(()=>void load().catch(e=>setError(String(e))),150);}});return()=>{clearTimeout(timer);off();};},[id]);
  useEffect(()=>{if(!property&&!menu?.row)return;let live=true;void window.localflow.notesList().then(async result=>{const nodes=flatten(result.items).filter(node=>node.kind==='database');if(live)setDestinations(nodes);if(property){const related=await Promise.all(nodes.map(async node=>({...((await window.localflow.notesDatabasePage({id:node.id,metadataOnly:true})).database),label:node.label})));if(live)setDatabases(current=>related.map(db=>({...db,rows:current.find(value=>value.id===db.id)?.rows||[]})));}}).catch(error=>{if(live)setError(String(error));});return()=>{live=false;};},[Boolean(property),Boolean(menu?.row)]);
  useEffect(()=>{const area=scrollArea.current;if(!area)return;const wheel=(event:WheelEvent)=>{if(event.shiftKey&&!event.deltaX&&area.scrollWidth>area.clientWidth){event.preventDefault();area.scrollLeft+=event.deltaY;}};area.addEventListener('wheel',wheel,{passive:false});return()=>area.removeEventListener('wheel',wheel);},[Boolean(database)]);
  const save = async (next: NotesDatabase, extra: Partial<DatabasePatch> = {}) => {
    if (pending || !database) return; setPending(true); setError('');
    try {
      await window.localflow.notesDatabasePatch({ id, revision: database.revision,
        ...(next.properties !== database.properties ? { properties: next.properties } : {}),
        ...(next.views !== database.views ? { views: next.views } : {}),
        rows: next.rows.filter(row => row !== database.rows.find(original => original.id === row.id)).map(row => ({ id: row.id, values: row.values })),
        deleteRows: database.rows.filter(row => !next.rows.some(next => next.id === row.id)).map(row => row.id), ...extra });
      await load();
    } catch (e) { setError(String(e)); } finally { setPending(false); }
  };
  const view = database?.views.find(v => v.id === viewId) || database?.views[0];
  const groupProperty = database?.properties.find(p => p.id === view?.groupBy) || database?.properties.find(p => ['status','select'].includes(p.type));
  const dateProperty = database?.properties.find(p => p.id === view?.dateProperty) || database?.properties.find(p => p.type === 'date');
  const rowGroups = useMemo(() => {
    const groups = new Map<string, DatabaseRow[]>((groupProperty?.options || []).map(option => [option.name, []]));
    const dates = new Map<string, DatabaseRow[]>();
    for (const row of rows) {
      const group = displayValue(row.values[groupProperty?.id || '']);
      const date = displayValue(row.values[dateProperty?.id || '']).slice(0,10);
      if (!groups.has(group)) groups.set(group, []);
      if (!dates.has(date)) dates.set(date, []);
      groups.get(group)!.push(row); dates.get(date)!.push(row);
    }
    return { groups, dates };
  }, [rows, groupProperty, dateProperty]);
  if (!database || database.id !== id || !view) return <div className="noteFolderState">{error || 'Loading database…'}</div>;
  const title = database.properties.find(p => p.type === 'title')!;
  const ordered=[...new Set([...(view.order || []),...database.properties.map(p=>p.id)])].map(id=>database.properties.find(p=>p.id===id)).filter((p):p is Property=>Boolean(p));
  const visible = ordered.filter(p => !view.visible || view.visible.includes(p.id) || p.type === 'title');
  const saveProperty=(p:Property)=>{const exists=database.properties.some(v=>v.id===p.id);const order=ordered.map(v=>v.id);if(!exists){const index=insertAt?order.indexOf(insertAt.id)+(insertAt.after?1:0):order.length;order.splice(Math.max(0,index),0,p.id);}void save({...database,properties:exists?database.properties.map(v=>v.id===p.id?p:v):[...database.properties,p],views:database.views.map(v=>v.id===view.id?{...v,order,visible:!exists&&v.visible?[...v.visible,p.id]:v.visible}:v)});setInsertAt(null);};
  const changeView=(next:DatabaseView)=>void save({...database,views:database.views.map(v=>v.id===next.id?next:v)});
  const reorder=(from:string,before:string)=>void save({...database,views:database.views.map(v=>v.id===view.id?{...v,sorts:[]}:v)},{reorder:{id:from,beforeId:before}});
  const action = async (value: Omit<DatabasePageAction, 'id' | 'revision'>) => { if (busy) return; setMenu(null); setPending(true); setError(''); try { await window.localflow.notesDatabasePageAction({ ...value, id, revision: database.revision }); await load(); } catch (e) { setError(String(e)); } finally { setPending(false); } };
  const removeRow=(row:DatabaseRow)=>action({action:'remove',rowId:row.id});
  const duplicateRow=(row:DatabaseRow)=>action({action:'duplicate',rowId:row.id});
  const moveRow=(row:DatabaseRow,targetId:string)=>action({action:'move',rowId:row.id,targetId});
  const run=(row:DatabaseRow,p:Property)=>void action({action:'run',rowId:row.id,propertyId:p.id});
  const updateCell = (row: DatabaseRow, property: Property, value: unknown) => void save({ ...database, rows: database.rows.map(r => r.id === row.id ? { ...r, values: { ...r.values, [property.id]: value } } : r) });
  const color = (row: DatabaseRow) => view.colors?.find(rule => matches(row.values, rule.filter))?.color;
  const addRow = () => action({action:'add'});
  const rowCard = (row: DatabaseRow) => <article key={row.id} className="databaseCard" onContextMenu={e=>{e.preventDefault();setMenu({row,x:e.clientX,y:e.clientY});}} draggable onDragStart={e => e.dataTransfer.setData('application/localflow-row', row.id)} style={{ backgroundColor: color(row) }}><button className="databaseCardMenu" aria-label="Row actions" onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();setMenu({row,x:rect.left,y:rect.bottom});}}><MoreHorizontal size={15}/></button><button className="databaseRowTitle" onClick={() => row.pageId && open(row.pageId)}>{displayValue(row.values[title.id]) || 'Untitled'}<ArrowUpRight size={13} /></button>{visible.filter(p => p.id !== title.id).slice(0,6).map(p => <div key={p.id}><small>{p.name}</small><span title={row.errors?.[p.id]}>{row.errors?.[p.id] ? `⚠ ${row.errors[p.id]}` : displayValue(row.values[p.id])}</span></div>)}</article>;
  const groups = [...rowGroups.groups.keys()];
  const table = (items:DatabaseRow[]) => <DatabaseTable rows={items} properties={visible} database={database} databases={databases} view={view} pending={busy} color={color} open={open} change={updateCell} changeView={changeView} rowMenu={(row,x,y)=>setMenu({row,x,y})} propertyMenu={(property,x,y)=>setMenu({property,x,y})} addProperty={()=>setProperty({id:crypto.randomUUID(),name:'',type:'text'})} reorder={reorder} run={run}/>;
  const exportCsv=()=>{void window.localflow.notesDatabaseExport(request.current).then(text=>window.localflow.exportText({text,defaultName:label.replace(/[<>:"/\\|?*]/g,'-')+'.csv'})).catch(e=>setError(String(e)));setMenu(null);};
  return <section className={`notesDatabasePage${embedded ? ' embeddedDatabase' : ''}`}>
    <header><Database size={22} /><h1>{label}</h1>{embedded && <button aria-label="Open database as page" title="Open as page" onClick={()=>open(id)}><ArrowUpRight size={16}/></button>}</header>
    {queryError && <div className="errorBox" role="alert">{queryError}<button onClick={() => setEditingView({ ...view, filter: undefined })}>Edit filter</button></div>}
    {error && <div className="errorBox" role="alert">{error}<button onClick={() => void load()}>Reload database</button></div>}
    <div className="databaseToolbar"><div role="tablist" aria-label="Database views">{database.views.map(v => <button key={v.id} role="tab" aria-selected={v.id===view.id} onContextMenu={e=>{e.preventDefault();setMenu({view:v,x:e.clientX,y:e.clientY});}} onClick={()=>{setViewId(v.id);setOffset(0);}} onDoubleClick={()=>setEditingView(structuredClone(v))}>{v.name}</button>)}<button aria-label="New database view" onClick={()=>setEditingView({id:crypto.randomUUID(),name:'New view',type:'table',sorts:[],colors:[]})}><Plus size={15}/></button></div>{showSearch&&<input autoFocus className="databaseSearch" aria-label="Search database" placeholder="Search" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}}/>}<button aria-label="Search database toggle" onClick={()=>{setShowSearch(!showSearch);setSearch('');}}><Search size={16}/></button><button className="databaseNewButton" aria-label="New row" disabled={busy} onClick={()=>void addRow()}><Plus size={14}/> New</button><button aria-label="Database actions" onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();setMenu({more:true,x:rect.right-240,y:rect.bottom});}}><MoreHorizontal size={17}/></button></div>
    {menu&&<DatabaseMenu x={menu.x} y={menu.y} close={()=>setMenu(null)}>
      {menu.more&&<><button onClick={()=>{setEditingView(structuredClone(view));setMenu(null);}}>Layout, properties & filters</button><button onClick={()=>{setProperty({id:crypto.randomUUID(),name:'',type:'text'});setMenu(null);}}>Add property</button><button onClick={()=>{changeView({...view,wrap:!view.wrap});setMenu(null);}}>{view.wrap?'Truncate cell content':'Wrap cell content'}</button><button onClick={exportCsv}>Export this view as CSV</button></>}
      {menu.row&&<><button disabled={!menu.row.pageId} onClick={()=>{open(menu.row!.pageId!);setMenu(null);}}>Open page</button><button disabled={busy} onClick={()=>void duplicateRow(menu.row!)}>Duplicate row</button><button disabled={busy||!neighbors[menu.row.id]?.before} onClick={()=>{reorder(menu.row!.id,neighbors[menu.row!.id].before!);setMenu(null);}}>Move up</button><button disabled={busy||!neighbors[menu.row.id]?.after} onClick={()=>{reorder(neighbors[menu.row!.id].after!,menu.row!.id);setMenu(null);}}>Move down</button><label>Move to database<select aria-label="Move row to database" value="" disabled={busy} onChange={e=>e.target.value&&void moveRow(menu.row!,e.target.value)}><option value="">Choose destination</option>{destinations.filter(db=>db.id!==id).map(db=><option key={db.id} value={db.id}>{db.label}</option>)}</select></label><hr/><button className="destructive" disabled={busy} onClick={()=>{const row=menu.row!;setMenu(null);setConfirmation({message:'Delete this row and its page?',action:()=>void removeRow(row)});}}>Delete row</button></>}
      {menu.property&&<><button onClick={()=>{setProperty(menu.property!);setMenu(null);}}>Edit property</button><button onClick={()=>{changeView({...view,sorts:[{property:menu.property!.id,direction:'asc'}]});setMenu(null);}}>Sort ascending</button><button onClick={()=>{changeView({...view,sorts:[{property:menu.property!.id,direction:'desc'}]});setMenu(null);}}>Sort descending</button><button onClick={()=>{setEditingView({...view,filter:{operator:'and',filters:[...(view.filter?[view.filter]:[]),{property:menu.property!.id,operator:'is',value:''}]}});setMenu(null);}}>Filter by this property</button><button onClick={()=>{setInsertAt({id:menu.property!.id,after:false});setProperty({id:crypto.randomUUID(),name:'',type:'text'});setMenu(null);}}>Insert property left</button><button onClick={()=>{setInsertAt({id:menu.property!.id,after:true});setProperty({id:crypto.randomUUID(),name:'',type:'text'});setMenu(null);}}>Insert property right</button><button disabled={menu.property.type==='title'} onClick={()=>{const original=menu.property!;let name=original.name+' (copy)';let n=2;while(database.properties.some(p=>p.name===name))name=original.name+' (copy '+(n++)+')';const copied={...structuredClone(original),id:crypto.randomUUID(),name};const order=ordered.map(p=>p.id);order.splice(order.indexOf(original.id)+1,0,copied.id);void save({...database,properties:[...database.properties,copied],views:database.views.map(v=>v.id===view.id?{...v,order,visible:v.visible?[...v.visible,copied.id]:v.visible}:v)},{copyProperty:{from:original.id,to:copied.id}});setMenu(null);}}>Duplicate property</button><button disabled={menu.property.type==='title'} onClick={()=>{changeView({...view,visible:visible.filter(p=>p.id!==menu.property!.id).map(p=>p.id)});setMenu(null);}}>Hide in this view</button><hr/><button className="destructive" disabled={menu.property.type==='title'} onClick={()=>{const p=menu.property!;setMenu(null);setConfirmation({message:`Delete ${p.name} and its values?`,action:()=>{const clean=(filter:import('../../lib/database').Condition|undefined):import('../../lib/database').Condition|undefined=>filter?.filters?{...filter,filters:filter.filters.map(clean).filter((f):f is import('../../lib/database').Condition=>Boolean(f))}:filter?.property===p.id?undefined:filter;void save({...database,properties:database.properties.filter(v=>v.id!==p.id),views:database.views.map(v=>({...v,visible:v.visible?.filter(key=>key!==p.id),order:v.order?.filter(key=>key!==p.id),widths:Object.fromEntries(Object.entries(v.widths||{}).filter(([key])=>key!==p.id)),groupBy:v.groupBy===p.id?undefined:v.groupBy,dateProperty:v.dateProperty===p.id?undefined:v.dateProperty,filter:clean(v.filter),sorts:v.sorts?.filter(s=>s.property!==p.id),colors:v.colors?.map(c=>({...c,filter:clean(c.filter)})).filter((c):c is {color:string;filter:import('../../lib/database').Condition}=>Boolean(c.filter))}))});}});}}>Delete property</button></>}
      {menu.view&&<><button onClick={()=>{setEditingView(structuredClone(menu.view!));setMenu(null);}}>Edit view</button><button onClick={()=>{const copied={...structuredClone(menu.view!),id:crypto.randomUUID(),name:menu.view!.name+' (copy)'};void save({...database,views:[...database.views,copied]});setViewId(copied.id);setMenu(null);}}>Duplicate view</button><button disabled={database.views.length===1} className="destructive" onClick={()=>{void save({...database,views:database.views.filter(v=>v.id!==menu.view!.id)});setMenu(null);}}>Delete view</button></>}
    </DatabaseMenu>}
    {confirmation&&<div className="databaseConfirmation" role="alertdialog" aria-label="Confirm database deletion"><p>{confirmation.message}</p><button onClick={()=>setConfirmation(null)}>Cancel</button><button className="destructive" onClick={()=>{confirmation.action();setConfirmation(null);}}>Delete</button></div>}
    {property && <PropertyEditor key={property.id} property={property} database={database} databases={databases} close={() => setProperty(null)} save={saveProperty} />}
    {editingView && <aside className="databaseViewSettings"><header><strong>View settings</strong><button aria-label="Close view settings" onClick={() => setEditingView(null)}>×</button></header><label>Name<input aria-label="View name" value={editingView.name} onChange={e => setEditingView({ ...editingView, name: e.target.value })} /></label><label>Layout<select aria-label="View layout" value={editingView.type} onChange={e => setEditingView({ ...editingView, type: e.target.value as DatabaseView['type'] })}>{['table','board','list','gallery','calendar','timeline','form'].map(t => <option key={t}>{t}</option>)}</select></label><label>Group by<select aria-label="Group by" value={editingView.groupBy || ''} onChange={e => setEditingView({ ...editingView, groupBy: e.target.value || undefined })}><option value="">None</option>{database.properties.filter(p => !['formula','rollup','files'].includes(p.type)).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{['calendar','timeline'].includes(editingView.type) && <label>Date property<select aria-label="Calendar date" value={editingView.dateProperty || dateProperty?.id || ''} onChange={e => setEditingView({ ...editingView, dateProperty: e.target.value })}>{database.properties.filter(p => p.type === 'date').map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
      <details><summary>Properties</summary>{database.properties.map(p => <label key={p.id}><input type="checkbox" checked={!editingView.visible || editingView.visible.includes(p.id) || p.type === 'title'} disabled={p.type === 'title'} onChange={e => setEditingView({ ...editingView, visible: e.target.checked ? [...(editingView.visible || database.properties.map(v => v.id)),p.id] : (editingView.visible || database.properties.map(v => v.id)).filter(id => id !== p.id) })} />{p.name}</label>)}</details>
      <details><summary>Filter</summary><Conditions properties={database.properties} value={editingView.filter || { operator: 'and', filters: [] }} onChange={filter => setEditingView({ ...editingView, filter })} /></details>
      <details><summary>Sort</summary>{(editingView.sorts || []).map((sort,i) => <div className="conditionRule" key={i}><select aria-label="Sort property" value={sort.property} onChange={e => setEditingView({ ...editingView, sorts: editingView.sorts!.map((s,n) => n === i ? { ...s, property: e.target.value } : s) })}>{database.properties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="Sort direction" value={sort.direction} onChange={e => setEditingView({ ...editingView, sorts: editingView.sorts!.map((s,n) => n === i ? { ...s, direction: e.target.value as 'asc' | 'desc' } : s) })}><option value="asc">Ascending</option><option value="desc">Descending</option></select><button onClick={() => setEditingView({ ...editingView, sorts: editingView.sorts!.filter((_,n) => n !== i) })}>×</button></div>)}<button onClick={() => setEditingView({ ...editingView, sorts: [...(editingView.sorts || []), { property: title.id, direction: 'asc' }] })}>+ Sort</button></details>
      <details><summary>Conditional color</summary>{(editingView.colors || []).map((rule,i) => <div className="databaseColorRule" key={i}><input aria-label="Conditional color" type="color" value={rule.color} onChange={e => setEditingView({ ...editingView, colors: editingView.colors!.map((r,n) => n === i ? { ...r,color:e.target.value } : r) })} /><Conditions value={rule.filter} properties={database.properties} onChange={filter => setEditingView({ ...editingView, colors: editingView.colors!.map((r,n) => n === i ? { ...r,filter } : r) })} /><button onClick={() => setEditingView({ ...editingView, colors: editingView.colors!.filter((_,n) => n !== i) })}>Remove rule</button></div>)}<button onClick={() => setEditingView({ ...editingView, colors: [...(editingView.colors || []), { color: '#293e34', filter: { property: title.id, operator: 'contains', value: '' } }] })}>+ Color rule</button></details>
      <button disabled={busy || !editingView.name.trim()} onClick={() => { void save({ ...database, views: database.views.some(v => v.id === editingView.id) ? database.views.map(v => v.id === editingView.id ? editingView : v) : [...database.views,editingView] }); setViewId(editingView.id); setEditingView(null); }}>Apply view</button>{database.views.length > 1 && database.views.some(v => v.id === editingView.id) && <button onClick={() => { void save({ ...database, views: database.views.filter(v => v.id !== editingView.id) }); setEditingView(null); setViewId(database.views.find(v => v.id !== editingView.id)!.id); }}>Delete view</button>}
    </aside>}
    <div className="databaseContent" ref={scrollArea} tabIndex={0} role="region" aria-label={`${label} database content`}>
      {view.type === 'table' && (view.groupBy ? groups.map(group => <details open key={group}><summary>{group || 'No value'}</summary>{table(rowGroups.groups.get(group) || [])}</details>) : table(rows))}
      {view.type === 'board' && <div className="databaseBoard">{groups.map(group => <section key={group} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); const row = database.rows.find(r => r.id === e.dataTransfer.getData('application/localflow-row')); if (row && groupProperty && ['status','select','text','title'].includes(groupProperty.type)) updateCell(row,groupProperty,group); }}><h3>{group || 'No value'} <small>{rowGroups.groups.get(group)!.length}</small></h3>{rowGroups.groups.get(group)!.map(rowCard)}</section>)}</div>}
      {['list','gallery'].includes(view.type) && <div className={`databaseCards ${view.type}`}>{rows.map(rowCard)}</div>}
      {view.type === 'calendar' && <><div className="databaseCalendarToolbar"><button aria-label="Previous month" onClick={() => changeMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><strong>{month.toLocaleDateString(undefined,{ month:'long',year:'numeric' })}</strong><button aria-label="Next month" onClick={() => changeMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div>{dateProperty ? <div className="databaseCalendar">{Array.from({ length: 7 },(_,i) => <strong key={i}>{new Date(2026,5,i+1).toLocaleDateString(undefined,{ weekday:'short' })}</strong>)}{Array.from({ length: 42 },(_,i) => { const date = new Date(month.getFullYear(),month.getMonth(),1 - (month.getDay()+6)%7 + i); const key = `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; return <div key={key} data-outside={date.getMonth() !== month.getMonth()} onDragOver={e => e.preventDefault()} onDrop={e => { const row=database.rows.find(r=>r.id===e.dataTransfer.getData('application/localflow-row')); if(row) updateCell(row,dateProperty,{ start:key }); }}><small>{date.getDate()}</small>{(rowGroups.dates.get(key) || []).map(rowCard)}</div>; })}</div> : <p>Add a date property to use this calendar.</p>}<details><summary>No date ({(rowGroups.dates.get('') || []).length})</summary>{(rowGroups.dates.get('') || []).map(rowCard)}</details></>}
      {view.type === 'timeline' && <TimelineView rows={rows} title={title} dateProperty={dateProperty} open={open} month={month} onMonthChange={changeMonth} earliestDate={earliestDate}/>}
      {view.type === 'form' && <DatabaseForm key={view.id} database={database} databases={databases} properties={visible} submitted={()=>void load()}/>}
      <nav className="databasePagination" aria-label="Database pages"><span>{total ? pageOffset+1 : 0}–{pageOffset+rows.length} of {total} rows</span><button aria-label="Previous database page" disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}>Previous</button><button aria-label="Next database page" disabled={busy||offset+rows.length>=total} onClick={()=>setOffset(offset+100)}>Next</button></nav><button className="databaseAddRow" disabled={busy} onClick={() => void addRow()}><Plus size={14} /> New row</button>
    </div>
  </section>;
}
