import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { X } from 'lucide-react';
import type { MarkdownNote } from '../../lib/workspace';
import { MarkdownContent } from '../MarkdownContent';

export type PageTool = 'history' | 'trash' | 'ai' | 'suggest' | 'translate' | 'info';
export function PageTools({ tool, note, close, refreshed }: { tool: PageTool; note: MarkdownNote | null; close: () => void; refreshed: (id?:string) => Promise<void> }) {
  const [error,setError] = useState(''), [busy,setBusy] = useState(false), [prompt,setPrompt] = useState(''), [result,setResult] = useState('');
  const [history,setHistory] = useState<Awaited<ReturnType<typeof window.localflow.notesHistory>>>([]);
  const [trash,setTrash] = useState<Awaited<ReturnType<typeof window.localflow.notesTrash>>>([]);
  const run = async (work:()=>Promise<void>) => { setBusy(true);setError('');try{await work();}catch(error){setError(error instanceof Error?error.message:String(error));}finally{setBusy(false);} };
  useEffect(() => { void run(async()=>{if(tool==='history' && note)setHistory(await window.localflow.notesHistory(note.id));if(tool==='trash')setTrash(await window.localflow.notesTrash());}); },[tool,note?.id]);
  const title = {history:'Version history',trash:'Trash',ai:'Use with AI',suggest:'Suggest edits',translate:'Translate page',info:'Page information'}[tool];
  const writing = tool === 'ai' || tool === 'suggest' || tool === 'translate';
  return createPortal(<div className="notesDialogBackdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)close();}}><div role="dialog" aria-modal="true" aria-label={title} className="notesPageDialog noteToolsDialog" onKeyDown={event=>{if(event.key==='Escape'&&!busy)close();}}>
    <button className="notesDialogClose" aria-label="Close page tools" disabled={busy} onClick={close}><X size={16}/></button><h3>{title}</h3>
    {error && <p role="alert">{error}</p>}
    {tool==='history' && <><p>Up to 20 recent saved versions, limited to 8 MB per page. Restoring also preserves the current version.</p>{!history.length && !busy && <p>No earlier saved versions yet.</p>}{history.map(value=><article className="noteVersion" key={value.revision}><strong>{value.label}</strong><time>{value.updatedAt?new Date(value.updatedAt).toLocaleString():''}</time><pre>{value.preview}</pre><button disabled={busy||note?.presentation?.locked} onClick={()=>void run(async()=>{await window.localflow.notesRestoreVersion({id:note!.id,revision:value.revision});await refreshed(note!.id);close();})}>Restore this version</button></article>)}</>}
    {tool==='trash' && <><p>Deleted pages and their children can be restored here.</p>{!trash.length && !busy && <p>Trash is empty.</p>}{trash.map(value=><article className="noteVersion" key={value.id}><strong>{value.label}</strong><time>{new Date(value.deletedAt).toLocaleString()}</time><button disabled={busy} onClick={()=>void run(async()=>{await window.localflow.notesRestore(value.id);await refreshed(value.id);setTrash(await window.localflow.notesTrash());})}>Restore page</button></article>)}</>}
    {writing && note && <><p>Uses your connected Codex account. Review the result before changing this page.</p><form onSubmit={event=>{event.preventDefault();void run(async()=>{setResult(await window.localflow.notesSkill({skill:tool==='suggest'?'suggest':'ask',text:note.content,prompt:tool==='translate'?`Translate the supplied page into the following requested language, preserving its Markdown structure: ${prompt}`:prompt}));});}}><label>{tool==='translate'?'Target language':'Instructions'}<textarea autoFocus aria-label={tool==='translate'?'Target language':'Writing instructions'} value={prompt} maxLength={10000} onChange={event=>setPrompt(event.target.value)} required={tool!=='suggest'} placeholder={tool==='translate'?'Any language…':'What would you like to change?'}/></label><button disabled={busy||!note.content.trim()||((tool==='ai'||tool==='translate')&&!prompt.trim())}>{busy?'Working…':'Generate preview'}</button></form>{result && <><div className="noteWritingPreview"><MarkdownContent content={result}/></div><div className="noteToolActions"><button disabled={busy} onClick={()=>void run(async()=>{await window.localflow.copyText(result);})}>Copy result</button><button disabled={busy} onClick={()=>void run(async()=>{const value=await window.localflow.notesCreate({label:`${note.label.slice(0,280)} (AI)`,content:result});await refreshed(value.id);close();})}>Save as new page</button><button disabled={busy||note.presentation?.locked} onClick={()=>void run(async()=>{await window.localflow.notesSave({...note,content:result,document:undefined,html:undefined});await refreshed(note.id);close();})}>Replace page contents</button></div></>}</>}
    {tool==='info' && note && <dl className="noteInfo"><dt>Title</dt><dd>{note.label}</dd><dt>Last edited</dt><dd>{note.updatedAt?new Date(note.updatedAt).toLocaleString():'—'}</dd><dt>Storage</dt><dd>{note.path}</dd><dt>Size (Markdown)</dt><dd>{new TextEncoder().encode(note.content).length.toLocaleString()} bytes</dd><dt>Children</dt><dd>{note.children?.length||0}</dd><dt>Offline</dt><dd>Page content is always stored locally. Remote linked media still needs its source.</dd><dt>Page link</dt><dd>localflow-note://{note.id}</dd></dl>}
  </div></div>,document.body);
}
