import { useState } from 'react';
import type { NotesDatabase, Property, PropertyType } from '../../lib/database';
import {ButtonActionsEditor} from './ButtonActionsEditor';
export function PropertyEditor({ property, database, databases, save, close }: { property: Property; database: NotesDatabase; databases: NotesDatabase[]; save: (property: Property) => void; close: () => void }) {
  const [draft, setDraft] = useState(property);
  const patch = (value: Partial<Property>) => setDraft({ ...draft, ...value });
  const target = databases.find(db => db.id === database.properties.find(p => p.id === draft.relation)?.target);
  return <form className="databasePropertyEditor" onSubmit={e => { e.preventDefault(); save(draft); close(); }}><label>Name<input aria-label="Property name" required autoFocus value={draft.name} onChange={e => patch({ name: e.target.value })} /></label><label>Type<select aria-label="Property type" value={draft.type} disabled={property.type === 'title'} onChange={e => patch({ type: e.target.value as PropertyType })}>{['title','text','number','select','multi_select','status','date','checkbox','url','email','phone','person','files','relation','formula','rollup','button'].filter(t => t !== 'title' || property.type === 'title').map(t => <option key={t} value={t}>{t.replace('_',' ')}</option>)}</select></label>
    {['select','multi_select','status'].includes(draft.type) && <label>Options (one per line)<textarea aria-label="Property options" value={(draft.options || []).map(o => o.name).join('\n')} onChange={e => patch({ options: [...new Set(e.target.value.split('\n'))].map(name => ({ name, color: draft.options?.find(option=>option.name===name)?.color })) })} /></label>}
    {draft.type === 'formula' && <label>Formula<textarea aria-label="Formula expression" placeholder={'if(prop("Amount") > 100, "High", "Low")'} value={draft.expression || ''} onChange={e => patch({ expression: e.target.value })} /></label>}
    {draft.type === 'relation' && <label>Database<select aria-label="Relation database" value={draft.target || ''} onChange={e => patch({ target: e.target.value })}><option value="">Select database</option>{databases.map(db => <option key={db.id} value={db.id}>{(db as NotesDatabase & { label?: string }).label || db.id}</option>)}</select></label>}
    {draft.type === 'rollup' && <><label>Relation<select aria-label="Rollup relation" value={draft.relation || ''} onChange={e => patch({ relation: e.target.value })}><option value="" />{database.properties.filter(p => p.type === 'relation').map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Property<select aria-label="Rollup property" value={draft.targetProperty || ''} onChange={e => patch({ targetProperty: e.target.value })}><option value="" />{target?.properties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Calculate<select aria-label="Rollup calculation" value={draft.aggregation || 'show'} onChange={e => patch({ aggregation: e.target.value })}>{['show','count','sum','average','min','max','percent_checked'].map(v => <option key={v} value={v}>{v}</option>)}</select></label></>}
    {draft.type==='button'&&<><label>Button label<input value={draft.buttonLabel||''} onChange={e=>patch({buttonLabel:e.target.value})}/></label><ButtonActionsEditor actions={draft.actions||[]} database={database} databases={databases} change={actions=>patch({actions,warning:undefined})}/></>}
    <button type="submit">Save property</button><button type="button" onClick={close}>Cancel</button>
  </form>;
}
