import { useState } from 'react';
import type { DatabaseRow, Property } from '../../lib/database';
import { displayValue } from '../../../electron/notes/database-engine.mjs';
export function TimelineView({rows,title,dateProperty,open}:{rows:DatabaseRow[];title:Property;dateProperty?:Property;open:(id:string)=>void}){
  const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
  if(!dateProperty)return <p>Add a date property to use this timeline.</p>;
  const start=month.getTime(),days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),day=86400000,end=start+days*day;
  const dated=rows.map(row=>{const value=row.values[dateProperty.id] as {start?:string;end?:string}|string;const a=Date.parse(typeof value==='string'?value:value?.start||'');const b=Date.parse(typeof value==='object'?value?.end||value?.start||'':value||'');return {row,a,b};});
  return <><div className="databaseCalendarToolbar"><button aria-label="Previous timeline month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><strong>{month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</strong><button aria-label="Next timeline month" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button><button onClick={()=>{const first=dated.filter(v=>Number.isFinite(v.a)).sort((a,b)=>a.a-b.a)[0];if(first){const date=new Date(first.a);setMonth(new Date(date.getFullYear(),date.getMonth(),1));}}}>First dated item</button></div><div className="databaseTimeline" style={{gridTemplateColumns:`180px repeat(${days}, minmax(30px,1fr))`}}><strong>Name</strong>{Array.from({length:days},(_,i)=><small key={i}>{i+1}</small>)}{dated.filter(v=>v.a<end&&v.b>=start).map(({row,a,b},i)=><div className="timelineRow" key={row.id}><button style={{gridRow:i+2,gridColumn:1}} onClick={()=>row.pageId&&open(row.pageId)}>{displayValue(row.values[title.id])||'Untitled'}</button><button className="timelineBar" style={{gridRow:i+2,gridColumn:`${Math.max(0,Math.floor((a-start)/day))+2} / ${Math.min(days,Math.floor((b-start)/day)+1)+2}`}} title={`${displayValue(row.values[title.id])}: ${new Date(a).toLocaleDateString()} – ${new Date(b).toLocaleDateString()}`} onClick={()=>row.pageId&&open(row.pageId)}>{displayValue(row.values[title.id])}</button></div>)}</div><details><summary>No date</summary>{dated.filter(v=>!Number.isFinite(v.a)).map(({row})=><button key={row.id} onClick={()=>row.pageId&&open(row.pageId)}>{displayValue(row.values[title.id])||'Untitled'}</button>)}</details></>;
}
